////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Order Component

The order manager allows you to enter and maintain orders, quotes, requests and report on them.

== Overview
TODO

== Orders management

=== Main screen
To select Sales and/or Purchase orders

=== Order View
This screen allow not only to view an order but also to change it

include::_include/order_report.adoc[leveloffset=+1]

== Requests

== Quotes

== Returns

== Requirements

== Stats