////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Accounting

The OFBiz accounting system is a core application component and has most of the
modern features you would expect in a general purpose double-entry accounting
system. However, OFBiz goes beyond that by and seamlessly integrates with other
OFBiz applications such as Inventory, Purchasing and Manufacturing to give your
business a complete ERP solution. This makes the system as a whole robust and 
integrated to provide more value than a plain accounting system.


include::_include/acc-intro.adoc[leveloffset=+1]

include::_include/acc-agreements.adoc[leveloffset=+1]

include::_include/acc-financial-accounts.adoc[leveloffset=+1]

include::_include/acc-global-settings.adoc[leveloffset=+1]
