= Apache OFBiz User Manual

== Introduction to OFBiz

Welcome to _Apache OFBiz_! A powerful top level Apache software project.
OFBiz is an Enterprise Resource Planning (ERP) System written in Java and
houses a large set of libraries, entities, services and features to run
all aspects of your business.

This manual will describe all aspects of this powerful ERP system. The manual
starts with the basics of what OFBiz and how it works, and describes high level
concepts like the entity engine, service engine, widget system and so on. In
addition the manual explains the core application of this framework like the
Party Manager, Order Manager, Accounting system, and others.

If you wish to contribute to OFBiz and help make it better, you may wish to read
the "Apache OFBiz Developer Manual" for a deeper understanding of the
architectural concepts of the framework.

=== What is Apache OFBiz

=== The main parts of Apache OFBiz

==== Web MVC Framework

==== Entity Engine

==== Service Engine

==== Widget System

==== Data Model Library

==== Service Library

==== Core Applications

==== Plugins

== Core Business Applications

include::../../applications/accounting/src/docs/asciidoc/accounting.adoc[leveloffset=+1]
include::../../applications/humanres/src/docs/asciidoc/humanres.adoc[leveloffset=+1]