/*******************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *******************************************************************************/
package org.apache.ofbiz.entity.condition;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import java.util.ArrayList;
import java.util.List;

import org.apache.ofbiz.entity.model.ModelField;
import org.junit.jupiter.api.Test;

/**
 * Regression tests for the SQL generated by an {@link EntityFunction} (e.g. UPPER/LOWER/TRIM)
 * that wraps a literal Java value rather than a nested field, as happens for ignore-case
 * comparisons such as those built by FindServices.createSingleCondition and by
 * LoginServices.createUserLogin's duplicate-userLoginId check.
 *
 * A caller that already knows the ModelField being compared against (i.e. it called
 * setModelField before addSqlValue) must get that value bound as a JDBC parameter, exactly
 * like the nested-field case does, rather than inlined as a SQL string literal.
 */
public class EntityFunctionTests {

    @Test
    public void literalValueWithKnownFieldIsBoundAsParameter() {
        ModelField field = ModelField.create(null, "userLoginId", "id-vlong", true);
        EntityFunction<String> upper = EntityFunction.upper("' OR (1=1) OR '");
        upper.setModelField(field);

        StringBuilder sql = new StringBuilder();
        List<EntityConditionParam> params = new ArrayList<>();
        upper.addSqlValue(sql, null, params, false, null);

        assertEquals("UPPER(?)", sql.toString());
        assertEquals(1, params.size());
        assertEquals(field, params.get(0).getModelField());
        assertEquals("' OR (1=1) OR '", params.get(0).getFieldValue());
    }

    @Test
    public void literalValueWithoutKnownFieldIsStillInlinedLikeBefore() {
        // Preserve existing behavior when no caller ever identifies a ModelField for this
        // EntityFunction: it still inlines, same as prior to the fix.
        EntityFunction<String> upper = EntityFunction.upper("O'BRIEN");

        StringBuilder sql = new StringBuilder();
        List<EntityConditionParam> params = new ArrayList<>();
        upper.addSqlValue(sql, null, params, false, null);

        assertEquals("UPPER('O''BRIEN')", sql.toString());
        assertFalse(sql.toString().contains("' OR"));
    }
}
