////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Find Employees
In this screen you can create a new employee, search for an  existing employee and view a list of employees.

Selecting an employee in the list opens the employee's profile and  other screens associated with the employee.

To find an employee enter the search criteria.

NOTE: Only Employees Are Found.If you want to locate people who are not employees then use the Party Manager application.

Fields

* Party ID - Must be the id of a party who is an employee.
* User Login - The identifier used to login to OFBiz. An employee may have zero or more user logins.
* Last name - Employee last name
* First name - Employee first name
