////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Simple Howto for Training UI
NOTE: TO CHECK for the moment, work in progress...

Introduction: Trainings in HR module includes Training Calendar where we can create new schedules from trainings
 available in an organization.

Admin can assign trainings & employee can request for scheduled trainings.

Employee can also check status of their training requests & assignments.

Need of Trainings in HR:

* Training and development of professionals fills up the skill gaps and further improve the levels of proficiency.
* Training and development manages constantly changing business and industrial scenario and therefore, matches with
  the requirements or demands of changes on the organizations.
* Creates a learning organization culture.

Organizational development:

* Organization decides to use certain initiatives and wants to train and develop a good number of people
  in the entire organization or the people in certain chosen departments or projects on those initiatives.
* Prepares the organization to meet the needs of legal/statutory requirements. Features of Trainings:
* New Trainings can be added/modified.
* Trainings can be scheduled in the calendar.
* Employees can apply to supervisor for available scheduled trainings but, cannot request same training event
  again to same approver
* Admin can assign trainings to Employees.
* Admin can approve/reject the trainings requested to him but, once rejected cannot be approved again.
* Employees can check the status of their training requests and Trainings assigned to them.

Road Ahead: Currently we have implemented Trainings under HR module.

We are working on the implementation of Training calendar in profile tab of Employee.

We are also planning to introduce trainer's information in training calendar.

== In "GlobalHRSetting"
. Admin can create & manage the trainings provided by the organization.
