////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Employee Profile
The Profile screen for an employee is a collection of screenlets each displaying information about a different aspect
 of the employee.

In this screen you can:

* View summary information about an employee
* Update employee personal information
* View, create, update, and expire employee contact information
* View and create a list of related accounts
* View training records
* View employment information
* View, create, and update login id's, update security group
* View and create party attributes
* Upload party content
* View and create notes
