////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Employee Positions
An employee position is also called a job position. It is a role that has been
created to perform a specific task within the Company. This means that it has
approved funding to pay it. +
Generally positions are authorized by a budget and fulfilled by people.
For the Company to engage one person to do a job. OFBiz handles positions in a flexible manner
 so you can think of a position as an authorization for a full-time equivalent (FTE)

Employee positions are defined by:

* the work description and responsibilities
* a pay structure (e.g. hourly wages, salary, contract etc)
* full-time or part-time
* the skills needed to fullfill the position

NOTE: An employee positions is not the same as a person fullfilling the role.
A person fulfilling an employee position is called an employee

An employee position can be fullfilled (i.e. someone is currently working in the
role) or it can be unfulfilled (i.e. a job vacancy).

NOTE: In some cases an employee position could also be considered a full-time
 equivalent (FTE) and can be assigned to more than one person (e.g. job sharing)

In the OFBiz Human Resources application

* an employee position have
** a type, defined in Global HR Settings, which describes the job and it's pay rates. +
   Some examples types could be secretary, production worker, sales manager, executive vice president or OFBiz programmer. +
   If more then one person is needed for a type of job then a position must be created for each required person :
   i.e. If 10 secretaries are authorized for the Human Resource department then 10 positions are created with type secretary.
** a reporting structure.  Positions report to other positions and not the people who hold the position. +
   You can identify / manage
*** the position to reports to
*** the positions(s), the current position manages.
*** in matrix orgnaization when there are multiple positions to report, most of time only one is the primary for the day to day
    approval (like holidays). It's the purpose of the flag primary
** a status, it can be one of: Planned For, Active/Open, or Inactive/Closed.
* you can:
** Create employee positions
** Fulfill employee positions
** Define the responsibilities of an employee position
** Define a tree reporting structure between employee positions
** Track employment position fulfillments over time


== Employee Position management in UI
=== List Employee Position
This screen displays a list of positions for an employee.

NOTE: Employee positions are created and managed in the 'Employee Position' menu option.

Details about the position are displayed including any related dates and  whether the position is temporary
 or not.

include::HELP-hr-EditEmplPosition.adoc[leveloffset=+2]

=== View Employee Position
This screen displays summary details about an Employee Position including details about who currently holds
the position, their responsibilities and  the reporting structure.
