////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Global HR Settings

Global HR Settings are used to setup the basic reference data that is used
throughout the Human Resources application. Many of the screens contain fields
that have drop-down lists for selection and these drop-down list can be setup
here.

TIP: You need to have 'administrator' or 'create privileges' to update any of
the Global HR Settings

== Employee Leave Type
Used by <<_leave, Employee Leave>> management to detail why is employee request a leave.

In this menu option you could manage (create / modify / delete) Leave Type and Leave Reason.

For some example, look at the Tutorial Employment and Salary <<_step_5_employee_leaves>>

=== Reason Type
To create or request a leave an employee could give the type of leave and the reason.

== Pay Grades
Useful to define a salary amount table for the company. With this table for each grade and a step
you have a amount.

It's used in structured entreprise to be more clear on salary definition or supplier cost.

Worksheet PayGrade - SalaryStep is not usable alone, when it's used to define a <<_rates>> it's associated
with PeriodType (per year, per month, per week, per hour) and RateType (Standard, Average, Hightest, lowest, ...). +
So sometine it's needed to define multiple Grades if it will be use with a specifics periodType,
ex: for developper, one Grade for using with «per month» and one Grade for using with «per hours»

=== Salary Steps
For each Grade, it possible to have multiple step. It's possible to have overlap in step betwwen to grade.

For more detail, look at the Tutorial Employment and Salary <<_step_1_pay_grade_and_salary_step>>


== Position Types
<<_employee_positions>> is associated with a Position Type to "pre-define" some informations about the Job Position.

Position Type can be use for legal purpose, like social classification or Union constrain to be able "classify" Job position.

=== Position Type Rate
When defining a Employee Position, Salary is one of the important point. Depending of company salary rules, most of time
there is not a salary associated with a Position but a range and some indicators.

So it's possible to associated to a position type some amount associated to a Rate Type (Standard, Average, Hightest, lowest, …​)
and a  PeriodType (per year, per month, per week, per hour).

It's also used by WorkEffort Component to manage cost for subcontractor, for example.

=== Position Type Grade
If company is very structured on the salary management and so mange Salary by <<_pay_grades, Grade-Step>>, it's possible to
associate a Position Type and a RateType a Grade-Step.

As business rules, it's not possible to have for the same RateType a amount and a Grade-Step.

=== Valid Responsibilities
It's possible to define some responsibilities for a Position Type, to constrain the responsibilities it is authorized to
associate to a Employee Position (which is associated to this Position Type).

== Skills Types

A skill type is used to define a skill group. Your employees, contractors and
partners may have hundreds of different of skills so skill types allows you to
organise these skills so they are manageable.

This is helpful for reporting on your companies skill inventory or searching for
 resources with the skill types needed for a job. You can search for skills types
and assign skills to people and organisations in the Skills feature.

TIP: You can manage the skills of an individual or an organisation in their
 profile in Party Manager uisng the Party Skills feature.
