////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Qualifications

Qualifications are a feature of the recruitment process that allows you to record
 the details of any qualifications held by job applicants or your existing
employees.

During the job application process, you may want to ensure that applicants have
a minimum set of qualifications as a requirement for a position. The details of
the qualifications for each applicant will need to be captured and if necessary,
verified.

For existing employees, details of qualifications during their employment with
your organisation can be added at any time.

In the case where qualifications expire if not renewed, you can also add an
expiry or renewal date.

