def rules = [
	AbcMetric: 'Checks the ABC size metric for methods/classes. A method (or "closure field") with an ABC score greater than the maxMethodAbcScore property (60) causes a violation. Likewise, a class that has an (average method) ABC score greater than the maxClassAverageMethodAbcScore property (60) causes a violation.',
	AbstractClassName: 'Verifies that the name of an abstract class matches a regular expression specified in the regex property. If that property is null or empty, then this rule is not applied (i.e., it does nothing). It defaults to null, so this rule must be explicitly configured to be active. This rule ignores interfaces.',
	AbstractClassWithPublicConstructor: 'Checks for abstract classes that define a public constructor, which is useless and confusing.',
	AbstractClassWithoutAbstractMethod: 'The abstract class does not contain any abstract methods. An abstract class suggests an incomplete implementation, which is to be completed by subclasses implementing the abstract methods. If the class is intended to be used as a base class only (not to be instantiated direcly) a protected constructor can be provided prevent direct instantiation.',
	AddEmptyString: 'Finds empty string literals which are being added. This is an inefficient way to convert any type to a String.',
	AssertWithinFinallyBlock: 'Checks for assert statements within a finally block. An assert can throw an exception, hiding the original exception, if there is one.',
	AssignCollectionSort: 'The Collections.sort() method mutates the list and returns the list as a value. If you are assigning the result of sort() to a variable, then you probably don\'t realize that you\'re also modifying the original list as well. This is frequently the cause of subtle bugs.',
	AssignCollectionUnique: 'The Collections.unique() method mutates the list and returns the list as a value. If you are assigning the result of unique() to a variable, then you probably don\'t realize that you\'re also modifying the original list as well. This is frequently the cause of subtle bugs.',
	AssignmentInConditional: 'An assignment operator (=) was used in a conditional test. This is usually a typo, and the comparison operator (==) was intended.',
	AssignmentToStaticFieldFromInstanceMethod: 'Checks for assignment to a static field from an instance method.',
	BigDecimalInstantiation: 'Checks for calls to the BigDecimal constructors that take a double parameter, which may result in an unexpected BigDecimal value.',
	BitwiseOperatorInConditional: 'Checks for bitwise operations in conditionals, if you need to do a bitwise operation then it is best practice to extract a temp variable.',
	BlankLineBeforePackage: 'Makes sure there are no blank lines before the package declaration of a source code file.',
	BlockEndsWithBlankLine: 'Checks that code blocks such as method bodies, closures and control structure bodies do not end with an empty line.',
	BlockStartsWithBlankLine: 'Checks that code blocks such as method bodies, closures and control structure bodies do not start with an empty line.',
	BooleanGetBoolean: 'This rule catches usages of java.lang.Boolean.getBoolean(String) which reads a boolean from the System properties. It is often mistakenly used to attempt to read user input or parse a String into a boolean. It is a poor piece of API to use; replace it with System.properties[\'prop\'].',
	BooleanMethodReturnsNull: 'Method with Boolean return type returns explicit null. A method that returns either Boolean.TRUE, Boolean.FALSE or null is an accident waiting to happen. This method can be invoked as though it returned a value of type boolean, and the compiler will insert automatic unboxing of the Boolean value. If a null value is returned, this will result in a NullPointerException.',
	BracesForClass: 'Checks the location of the opening brace ({) for classes. By default, requires them on the same line, but the sameLine property can be set to false to override this.',
	BracesForForLoop: 'Checks the location of the opening brace ({) for for loops. By default, requires them on the same line, but the sameLine property can be set to false to override this.',
	BracesForIfElse: 'Checks the location of the opening brace ({) for if statements. By default, requires them on the same line, but the sameLine property can be set to false to override this.',
	BracesForMethod: 'Checks the location of the opening brace ({) for constructors and methods. By default, requires them on the same line, but the sameLine property can be set to false to override this.',
	BracesForTryCatchFinally: 'Checks the location of the opening brace ({) for try statements. By default, requires them on the line, but the sameLine property can be set to false to override this.',
	BrokenNullCheck: 'Looks for faulty checks for null that can cause a NullPointerException.',
	BrokenOddnessCheck: 'The code uses x % 2 == 1 to check to see if a value is odd, but this won\'t work for negative numbers (e.g., (-5) % 2 == -1). If this code is intending to check for oddness, consider using x & 1 == 1, or x % 2 != 0.',
	BuilderMethodWithSideEffects: 'A builder method is defined as one that creates objects. As such, they should never be of void return type. If a method is named build, create, or make, then it should always return a value.',
	BusyWait: 'Busy waiting (forcing a Thread.sleep() while waiting on a condition) should be avoided. Prefer using the gate and barrier objects in the java.util.concurrent package.',
	CatchArrayIndexOutOfBoundsException: 'Check the size of the array before accessing an array element rather than catching ArrayIndexOutOfBoundsException.',
	CatchError: 'Catching Error is dangerous; it can catch exceptions such as ThreadDeath and OutOfMemoryError.',
	CatchException: 'Catching Exception is often too broad or general. It should usually be restricted to framework or infrastructure code, rather than application code.',
	CatchIllegalMonitorStateException: 'Dubious catching of IllegalMonitorStateException. IllegalMonitorStateException is generally only thrown in case of a design flaw in your code (calling wait or notify on an object you do not hold a lock on).',
	CatchIndexOutOfBoundsException: 'Check that an index is valid before accessing an indexed element rather than catching IndexOutOfBoundsException.',
	CatchNullPointerException: 'Catching NullPointerException is never appropriate. It should be avoided in the first place with proper null checking, and it can mask underlying errors.',
	CatchRuntimeException: 'Catching RuntimeException is often too broad or general. It should usually be restricted to framework or infrastructure code, rather than application code.',
	CatchThrowable: 'Catching Throwable is dangerous; it can catch exceptions such as ThreadDeath and OutOfMemoryError.',
	ChainedTest: 'A test method that invokes another test method is a chained test; the methods are dependent on one another. Tests should be isolated, and not be dependent on one another.',
	ClassEndsWithBlankLine: 'Check whether the class ends with a blank line.By default, it enforces that there must be a blank line before the closing class brace, except if the class is empty and is written in a single line. A blank line is defined as any line that does not contain any visible characters.',
	ClassForName: 'Using Class.forName(...) is a common way to add dynamic behavior to a system. However, using this method can cause resource leaks because the classes can be pinned in memory for long periods of time.',
	ClassJavadoc: 'Makes sure each class and interface definition is preceded by javadoc. Enum definitions are not checked, due to strange behavior in the Groovy AST.',
	ClassName: 'Verifies that the name of a class matches a regular expression. By default it checks that the class name starts with an uppercase letter and is followed by zero or more word characters (letters, numbers or underscores). The regex property specifies the regular expression used to validate the class name.',
	ClassNameSameAsFilename: 'Reports files containing only one top level class / enum / interface which is named differently than the file.',
	ClassNameSameAsSuperclass: 'Checks for any class that has an identical name to its superclass, other than the package. This can be very confusing.',
	ClassSize: 'Checks if the size of a class exceeds the number of lines specified by the maxLines property (1000).',
	ClassStartsWithBlankLine: 'Check whether the class starts with a blank line By default, it enforces that there must be a blank line after the opening class brace, except if the class is empty and is written in a single line. A blank line is defined as any line that does not contain any visible characters.',
	CloneWithoutCloneable: 'The method clone() should only be declared if the class implements the Cloneable interface.',
	CloneableWithoutClone: 'A class that implements java.lang.Cloneable should define a clone() method.',
	CloseWithoutCloseable: 'If a class defines a "void close()" then that class should implement java.io.Closeable or java.lang.AutoCloseable.',
	ClosureAsLastMethodParameter: 'If a method is called and the last parameter is an inline closure then it can be declared outside of the method call brackets.',
	ClosureStatementOnOpeningLineOfMultipleLineClosure: 'Checks for closure logic on first line (after ->) for a multi-line closure.',
	CollectAllIsDeprecated: 'collectAll{} is deprecated since Groovy 1.8.1. Use collectNested instead{}.',
	CompareToWithoutComparable: 'If you implement a compareTo method then you should also implement the Comparable interface. If you don\'t then you could possibly get an exception if the Groovy == operator is invoked on your object. This is an issue fixed in Groovy 1.8 but present in previous versions.',
	ComparisonOfTwoConstants: 'Checks for expressions where a comparison operator or equals() or compareTo() is used to compare two constants to each other or two literals that contain only constant values., e.g.: 23 == 67, Boolean.FALSE != false, 0.17 <= 0.99, "abc" > "ddd", [a:1] <=> [a:2], [1,2].equals([3,4]) or [a:false, b:true].compareTo([\'a\':34.5, b:Boolean.TRUE].',
	ComparisonWithSelf: 'Checks for expressions where a comparison operator or equals() or compareTo() is used to compare a variable to itself, e.g.: x == x, x != x, x <=> x, x < x, x =>= x, x.equals(x) or x.compareTo(x), where x is a variable.',
	CompileStatic: 'Check that classes are explicitely annotated with either @GrailsCompileStatic, @CompileStatic or @CompileDynamic',
	ConfusingClassNamedException: 'This class is not derived from another exception, but ends with \'Exception\'. This will be confusing to users of this class.',
	ConfusingMethodName: 'Checks for confusing method names. The referenced methods have names that differ only by capitalization. This is very confusing because if the capitalization were identical then one of the methods would override the other.',
	ConfusingMultipleReturns: 'Multiple return values can be used to set several variables at once. To use multiple return values, the left hand side of the assignment must be enclosed in parenthesis. If not, then you are not using multiple return values, you\'re only assigning the last element.',
	ConfusingTernary: 'In a ternary expression avoid negation in the test. For example, rephrase: "(x != y) ? diff : same" as: "(x == y) ? same : diff". Consistent use of this rule makes the code easier to read. Also, this resolves trivial ordering problems, such as "does the error case go first?" or "does the common case go first?".',
	ConsecutiveBlankLines: 'Makes sure there are no consecutive lines that are either blank or whitespace only.',
	ConsecutiveLiteralAppends: 'Violations occur when method calls to append(Object) are chained together with literals as parameters. The chained calls can be joined into one invocation.',
	ConsecutiveStringConcatenation: 'Catches concatenation of two string literals on the same line. These can safely by joined.',
	ConstantAssertExpression: 'Checks for assert statements where the assert boolean condition expression is a constant or literal value.',
	ConstantIfExpression: 'Checks for if statements with a constant value for the if expression, such as true, false, null, or a literal constant value.',
	ConstantTernaryExpression: 'Checks for ternary expressions with a constant value for the boolean expression, such as true, false, null, or a literal constant value.',
	ConstantsOnlyInterface: 'An interface should be used only to model a behaviour of a class: using an interface as a container of constants is a poor usage pattern.',
	CouldBeElvis: 'Catch an if block that could be written as an elvis expression.',
	CouldBeSwitchStatement: 'Checks for multiple if statements that could be converted to a switch',
	CoupledTestCase: 'This rule finds test cases that are coupled to other test cases, either by invoking static methods on another test case or by creating instances of another test case. If you require shared logic in test cases then extract that logic to a new class where it can properly be reused.',
	CrapMetric: 'Checks the CRAP (Change Risk Anti-Patterns) score for methods/classes. The CRAP metric score is based on the cyclomatic complexity and test coverage for individual methods. A method with a CRAP value greater than the maxMethodCrapScore property (30) causes a violation. Likewise, a class that has an (average method) CRAP value greater than the maxClassAverageMethodCrapScore property (30) causes a violation.',
	CyclomaticComplexity: 'Checks the cyclomatic complexity for methods/classes.A method (or "closure field") with a cyclomatic complexity value greater than the maxMethodComplexity property (20) causes a violation. Likewise, a class that has an (average method) cyclomatic complexityvalue greater than the maxClassAverageMethodComplexity property (20) causes a violation.',
	DeadCode: 'Dead code appears after a return statement or an exception is thrown. If code appears after one of these statements then it will never be executed and can be safely deleted.',
	DirectConnectionManagement: 'The J2EE standard requires that applications use the container\'s resource management facilities to obtain connections to resources. Every major web application container provides pooled database connection management as part of its resource management framework. Duplicating this functionality in an application is difficult and error prone, which is part of the reason it is forbidden under the J2EE standard.',
	DoubleCheckedLocking: 'This rule detects double checked locking, where a \'lock hint\' is tested for null before initializing an object within a synchronized block. Double checked locking does not guarantee correctness and is an anti-pattern.',
	DoubleNegative: 'There is no point in using a double negative, it is always positive. For instance !!x can always be simplified to x. And !(!x) can as well.',
	DuplicateCaseStatement: 'Check for duplicate case statements in a switch block, such as two equal integers or strings.',
	DuplicateImport: 'Duplicate import statements are unnecessary.',
	DuplicateListLiteral: 'Code containing duplicate List literals can usually be improved by declaring the List as a constant field.',
	DuplicateMapKey: 'A map literal is created with duplicated key. The map entry will be overwritten.',
	DuplicateMapLiteral: 'Code containing duplicate Map literals can usually be improved by declaring the Map as a constant field.',
	DuplicateNumberLiteral: 'Code containing number String literals can usually be improved by declaring the number as a constant field. The ignoreNumbers property (0,1) can optionally specify a comma-separated list of numbers to ignore.',
	DuplicateSetValue: 'A Set literal is created with duplicate constant value. A set cannot contain two elements with the same value.',
	DuplicateStringLiteral: 'Code containing duplicate String literals can usually be improved by declaring the String as a constant field. The ignoreStrings property () can optionally specify a comma-separated list of Strings to ignore.',
	ElseBlockBraces: 'Use braces for else blocks, even for a single statement. By default, braces are not required for an else if it is followed immediately by an if. Set the bracesRequiredForElseIf property to true to require braces is that situation as well.',
	EmptyCatchBlock: 'In most cases, exceptions should not be caught and ignored (swallowed).',
	EmptyClass: 'Reports classes without methods, fields or properties. Why would you need a class like this?',
	EmptyElseBlock: 'Empty else blocks are confusing and serve no purpose.',
	EmptyFinallyBlock: 'Empty finally blocks are confusing and serve no purpose.',
	EmptyForStatement: 'Empty for statements are confusing and serve no purpose.',
	EmptyIfStatement: 'Empty if statements are confusing and serve no purpose.',
	EmptyInstanceInitializer: 'An empty class instance initializer was found. It is safe to remove it.',
	EmptyMethod: 'A method was found without an implementation. If the method is overriding or implementing a parent method, then mark it with the @Override annotation.',
	EmptyMethodInAbstractClass: 'An empty method in an abstract class should be abstract instead, as developer may rely on this empty implementation rather than code the appropriate one.',
	EmptyStaticInitializer: 'An empty static initializer was found. It is safe to remove it.',
	EmptySwitchStatement: 'Empty switch statements are confusing and serve no purpose.',
	EmptySynchronizedStatement: 'Empty synchronized statements are confusing and serve no purpose.',
	EmptyTryBlock: 'Empty try blocks are confusing and serve no purpose.',
	EmptyWhileStatement: 'Empty while statements are confusing and serve no purpose.',
	EnumCustomSerializationIgnored: 'Checks for enums that define writeObject() or writeReplace() methods, or declare serialPersistentFields or serialVersionUID fields, all of which are ignored for enums.',
	EqualsAndHashCode: 'If either the boolean equals(Object) or the int hashCode() methods are overridden within a class, then both must be overridden.',
	EqualsOverloaded: 'The class has an equals method, but the parameter of the method is not of type Object. It is not overriding equals but instead overloading it.',
	ExceptionExtendsError: 'Errors are system exceptions. Do not extend them.',
	ExceptionExtendsThrowable: 'Checks for classes that extend java.lang.Throwable. Custom exception classes should subclass java.lang.Exception or one of its descendants.',
	ExceptionNotThrown: 'Checks for an exception constructor call without a throw as the last statement within a catch block.',
	ExplicitArrayListInstantiation: 'This rule checks for the explicit instantiation of an ArrayList using the no-arg constructor. In Groovy, it is best to write new ArrayList() as [], which creates the same object.',
	ExplicitCallToAndMethod: 'This rule detects when the and(Object) method is called directly in code instead of using the & operator. A groovier way to express this: a.and(b) is this: a & b',
	ExplicitCallToCompareToMethod: 'This rule detects when the compareTo(Object) method is called directly in code instead of using the <=>, >, >=, <, and <= operators. A groovier way to express this: a.compareTo(b) is this: a <=> b, or using the other operators.',
	ExplicitCallToDivMethod: 'This rule detects when the div(Object) method is called directly in code instead of using the / operator. A groovier way to express this: a.div(b) is this: a / b',
	ExplicitCallToEqualsMethod: 'This rule detects when the equals(Object) method is called directly in code instead of using the == or != operator. A groovier way to express this: a.equals(b) is this: a == b and a groovier way to express : !a.equals(b) is : a != b',
	ExplicitCallToGetAtMethod: 'This rule detects when the getAt(Object) method is called directly in code instead of using the [] index operator. A groovier way to express this: a.getAt(b) is this: a[b]',
	ExplicitCallToLeftShiftMethod: 'This rule detects when the leftShift(Object) method is called directly in code instead of using the << operator. A groovier way to express this: a.leftShift(b) is this: a << b',
	ExplicitCallToMinusMethod: 'This rule detects when the minus(Object) method is called directly in code instead of using the - operator. A groovier way to express this: a.minus(b) is this: a - b',
	ExplicitCallToModMethod: 'This rule detects when the mod(Object) method is called directly in code instead of using the % operator. A groovier way to express this: a.mod(b) is this: a % b',
	ExplicitCallToMultiplyMethod: 'This rule detects when the minus(Object) method is called directly in code instead of using the * operator. A groovier way to express this: a.multiply(b) is this: a * b',
	ExplicitCallToOrMethod: 'This rule detects when the or(Object) method is called directly in code instead of using the | operator. A groovier way to express this: a.or(b) is this: a | b',
	ExplicitCallToPlusMethod: 'This rule detects when the plus(Object) method is called directly in code instead of using the + operator. A groovier way to express this: a.plus(b) is this: a + b',
	ExplicitCallToPowerMethod: 'This rule detects when the power(Object) method is called directly in code instead of using the ** operator. A groovier way to express this: a.power(b) is this: a ** b',
	ExplicitCallToPutAtMethod: 'Detects when the putAt(Object, Object) method is called directly in code instead of using the [] index operator. A groovier way to express this: map.putAt(k, v) is this: map[k] = v.',
	ExplicitCallToRightShiftMethod: 'This rule detects when the rightShift(Object) method is called directly in code instead of using the >> operator. A groovier way to express this: a.rightShift(b) is this: a >> b',
	ExplicitCallToXorMethod: 'This rule detects when the xor(Object) method is called directly in code instead of using the ^ operator. A groovier way to express this: a.xor(b) is this: a ^ b',
	ExplicitGarbageCollection: 'Calls to System.gc(), Runtime.getRuntime().gc(), and System.runFinalization() are not advised. Code should have the same behavior whether the garbage collection is disabled using the option -Xdisableexplicitgc or not. Moreover, "modern" jvms do a very good job handling garbage collections. If memory usage issues unrelated to memory leaks develop within an application, it should be dealt with JVM options rather than within the code itself.',
	ExplicitHashMapInstantiation: 'This rule checks for the explicit instantiation of a HashMap using the no-arg constructor. In Groovy, it is best to write new HashMap() as [:], which creates the same object.',
	ExplicitHashSetInstantiation: 'This rule checks for the explicit instantiation of a HashSet using the no-arg constructor. In Groovy, it is best to write new HashSet() as [] as Set, which creates the same object.',
	ExplicitLinkedHashMapInstantiation: 'This rule checks for the explicit instantiation of a LinkedHashMap using the no-arg constructor. In Groovy, it is best to write new LinkedHashMap() as [:], which creates the same object.',
	ExplicitLinkedListInstantiation: 'This rule checks for the explicit instantiation of a LinkedList using the no-arg constructor. In Groovy, it is best to write new LinkedList() as [] as Queue, which creates the same object.',
	ExplicitStackInstantiation: 'This rule checks for the explicit instantiation of a Stack using the no-arg constructor. In Groovy, it is best to write new Stack() as [] as Stack, which creates the same object.',
	ExplicitTreeSetInstantiation: 'This rule checks for the explicit instantiation of a TreeSet using the no-arg constructor. In Groovy, it is best to write new TreeSet() as [] as SortedSet, which creates the same object.',
	FactoryMethodName: 'A factory method is a method that creates objects, and they are typically named either buildFoo(), makeFoo(), or createFoo(). This rule enforces that only one naming convention is used. It defaults to makeFoo(), but that can be changed using the property \'regex\'.',
	FieldName: 'Verifies that the name of each field matches a regular expression. By default it checks that non-\'final\' field names start with a lowercase letter and contains only letters or numbers, and \'final\' field names start with an uppercase letter and contain only uppercase letters, numbers and underscores. The regex property specifies the default regular expression used to validate field names. The finalRegex property specifies the regular expression to validate \'final\' field names. The staticRegex property specifies the regular expression to validate \'static\' field names. The staticFinalRegex property specifies the regular expression to validate \'static final\' field names. The ignoreFieldNames property (serialVersionUID)can specify field names that should be ignored, optionally containing wildcard characters (\'*\' or \'?\').',
	FieldTypeRequired: 'Checks that field types are explicitly specified (and not using def).',
	FileCreateTempFile: 'The File.createTempFile() method is insecure, and has been deprecated by the ESAPI secure coding library. It has been replaced by the ESAPI Randomizer.getRandomFilename(String) method.',
	FileEndsWithoutNewline: 'Makes sure the source code file ends with a newline character.',
	FinalClassWithProtectedMember: 'This rule finds classes marked final that contain protected methods. If a class is final then it may not be subclassed, and there is therefore no point in having a method with protected visibility. Either the class should not be final or the method should be private or protected.',
	ForLoopShouldBeWhileLoop: 'A for loop without an init and update statement can be simplified to a while loop.',
	ForStatementBraces: 'Use braces for for statements, even for a single statement.',
	GStringAsMapKey: 'A GString should not be used as a map key since its hashcode is not guaranteed to be stable. Consider calling key.toString().',
	GStringExpressionWithinString: 'Check for regular (single quote) strings containing a GString-type expression (${...}).',
	GetterMethodCouldBeProperty: 'If a class defines a public method that follows the Java getter notation, and returns a constant, then it is cleaner to provide a Groovy property for the value rather than a Groovy method.',
	GrailsDomainHasEquals: 'Checks that Grails domain classes redefine equals().',
	GrailsDomainHasToString: 'Checks that Grails domain classes redefine toString()',
	GrailsDomainReservedSqlKeywordName: 'Forbids usage of SQL reserved keywords as class or field names in Grails domain classes. Naming a domain class (or its field) with such a keyword causes SQL schema creation errors and/or redundant table/column name mappings.',
	GrailsDomainStringPropertyMaxSize: 'String properties in Grails domain classes have to define maximum size otherwise the property is mapped to VARCHAR(255) causing runtime exceptions to occur',
	GrailsDomainWithServiceReference: 'Checks that Grails domain classes do not have service classes injected.',
	GrailsDuplicateConstraint: 'Check for duplicate entry in domain class constraints',
	GrailsDuplicateMapping: 'Check for duplicate name in a domain class mapping',
	GrailsMassAssignment: 'Untrusted input should not be allowed to set arbitrary object fields without restriction.',
	GrailsServletContextReference: 'Checks for references to the servletContext object from within Grails controller and taglib classes.',
	GrailsStatelessService: 'Checks for fields on Grails service classes. Grails service classes are singletons, by default, and so they should be reentrant and typically stateless. The ignoreFieldNames property (dataSource,scope,sessionFactory,transactional,*Service,grailsApplication) specifies one or more field names that should be ignored. The ignoreFieldTypes property (null) specifies one or more field type names that should be ignored. Both can optionally contain wildcard characters (\'*\' or \'?\').',
	GroovyLangImmutable: 'The groovy.lang.Immutable annotation has been deprecated and replaced by groovy.transform.Immutable. Do not use the Immutable in groovy.lang.',
	HardCodedWindowsFileSeparator: 'This rule finds usages of a Windows file separator within the constructor call of a File object. It is better to use the Unix file separator or use the File.separator constant.',
	HardCodedWindowsRootDirectory: 'This rule find cases where a File object is constructed with a windows-based path. This is not portable, and using the File.listRoots() method is a better alternative.',
	HashtableIsObsolete: 'The java.util.Hashtable class is effectively obsolete. Use the Java Collections Framework classes instead, including HashMap or ConcurrentHashMap. See the JDK javadoc.',
	IfStatementBraces: 'Use braces for if statements, even for a single statement.',
	IfStatementCouldBeTernary: 'Checks for if statements where both the if and else blocks contain only a single return statement with a constant or literal value',
	IllegalClassMember: 'Checks for classes containing fields/properties/methods matching configured illegal member modifiers or not matching any of the configured allowed member modifiers.',
	IllegalClassReference: 'Checks for reference to any of the classes configured in classNames.',
	IllegalPackageReference: 'Checks for reference to any of the packages configured in packageNames.',
	IllegalRegex: 'Checks for a specified illegal regular expression within the source code. The regex property specifies the regular expression to check for. It is required and cannot be null or empty.',
	IllegalString: 'Checks for a specified illegal string within the source code.',
	IllegalSubclass: 'Checks for classes that extend one of the specified set of illegal superclasses configured in superclassNames.',
	ImplementationAsType: 'Checks for use of a predefined set of concrete classes (e.g. ArrayList, Hashtable, ConcurrentHashMap) when specifying the type of a method parameter, closure parameter, constructor parameter, method return type or field type. The associated interfaces should be used to specify the type instead.',
	ImplicitClosureParameter: 'Checks that the implicit it closure parameter is not used and that parameters are declared explicitly instead.',
	ImportFromSamePackage: 'An import of a class that is within the same package is unnecessary.',
	ImportFromSunPackages: 'Avoid importing anything from the \'sun.*\' packages. These packages are not portable and are likely to change.',
	InconsistentPropertyLocking: 'Class contains similarly-named get and set methods where one method of the pair is marked either @WithReadLock or @WithWriteLock and the other is not locked at all.',
	InconsistentPropertySynchronization: 'Class contains similarly-named get and set methods where the set method is synchronized and the get method is not, or the get method is synchronized and the set method is not.',
	Indentation: 'Check indentation for class and method declarations, and initial statements.',
	InsecureRandom: 'Reports usages of java.util.Random, which can produce very predictable results. If two instances of Random are created with the same seed and sequence of method calls, they will generate the exact same results. Use java.security.SecureRandom instead, which provides a cryptographically strong random number generator. SecureRandom uses PRNG, which means they are using a deterministic algorithm to produce a pseudo-random number from a true random seed. SecureRandom produces non-deterministic output.',
	Instanceof: 'Checks for use of the instanceof operator. Use the ignoreTypeNames property to configure ignored type names.',
	IntegerGetInteger: 'This rule catches usages of java.lang.Integer.getInteger(String, ...) which reads an Integer from the System properties. It is often mistakenly used to attempt to read user input or parse a String into an Integer. It is a poor piece of API to use; replace it with System.properties[\'prop\'].',
	InterfaceName: 'Verifies that the name of an interface matches a regular expression specified in the regex property. If that property is null or empty, then this rule is not applied (i.e., it does nothing). It defaults to null, so this rule must be explicitly configured to be active.',
	InterfaceNameSameAsSuperInterface: 'Checks for any interface that has an identical name to its super-interface, other than the package. This can be very confusing.',
	InvertedCondition: 'An inverted condition is one where a constant expression is used on the left hand side of the equals comparision. Such conditions can be confusing especially when used in assertions where the expected value is by convention placed on the right hand side of the comparision.',
	InvertedIfElse: 'An inverted if-else statement is one in which there is a single if statement with a single else branch and the boolean test of the if is negated. For instance if (!x) false else true. It is usually clearer to write this as if (x) true else false.',
	JUnitAssertAlwaysFails: 'Checks for JUnit assert() method calls with constant arguments such that the assertion always fails. This includes: assertTrue(false), assertFalse(true) and assertNull(CONSTANT).',
	JUnitAssertAlwaysSucceeds: 'Checks for JUnit assert() method calls with constant arguments such that the assertion always succeeds. This includes: assertTrue(true), assertFalse(false) and assertNull(null).',
	JUnitAssertEqualsConstantActualValue: 'Reports usages of org.junit.Assert.assertEquals([message,] expected, actual) where the \'actual\' parameter is a constant or a literal. Most likely it was intended to be the \'expected\' value.',
	JUnitFailWithoutMessage: 'This rule detects JUnit calling the fail() method without an argument. For better error reporting you should always provide a message.',
	JUnitLostTest: 'Checks for classes that import JUnit 4 classes and contain a public, instance, void, no-arg method named test* that is not annotated with @Test.',
	JUnitPublicField: 'Checks for public field on a JUnit test class',
	JUnitPublicNonTestMethod: 'Checks if a JUnit test class contains public methods other than standard test methods, JUnit framework methods or methods with JUnit annotations.',
	JUnitPublicProperty: 'Checks for public properties defined on JUnit test classes. There should be no need to expose a public property on a test class.',
	JUnitSetUpCallsSuper: 'Checks that if the JUnit setUp() method is defined, that it includes a call to super.setUp().',
	JUnitStyleAssertions: 'This rule detects calling JUnit style assertions like assertEquals, assertTrue, assertFalse, assertNull, assertNotNull. Groovy 1.7 ships with a feature called the "power assert", which is an assert statement with better error reporting. This is preferable to the JUnit assertions.',
	JUnitTearDownCallsSuper: 'Checks that if the JUnit tearDown() method is defined, that it includes a call to super.tearDown().',
	JUnitTestMethodWithoutAssert: 'This rule searches for test methods that do not contain assert statements. Either the test method is missing assert statements, which is an error, or the test method contains custom assert statements that do not follow a proper assert naming convention. Test methods are defined as public void methods that begin with the work test or have a @Test annotation. By default this rule applies to the default test class names, but this can be changed using the rule\'s applyToClassNames property.',
	JUnitUnnecessarySetUp: 'Checks for JUnit setUp() methods that contain only a call to super.setUp().',
	JUnitUnnecessaryTearDown: 'Checks for JUnit tearDown() methods that contain only a call to super.tearDown().',
	JUnitUnnecessaryThrowsException: 'Check for throws clauses on JUnit test methods. That is not necessary in Groovy.',
	JavaIoPackageAccess: 'This rule reports violations of the Enterprise JavaBeans specification by using the java.io package to access files or the file system.',
	JavadocConsecutiveEmptyLines: 'Checks for javadoc comments with more than one consecutive empty line.',
	JavadocEmptyAuthorTag: 'Checks for empty @author tags within javadoc.',
	JavadocEmptyExceptionTag: 'Checks for empty @exception tag within javadoc.',
	JavadocEmptyFirstLine: 'Check for javadoc comments with an empty top line.',
	JavadocEmptyLastLine: 'Check for javadoc comments with an empty line at the bottom.',
	JavadocEmptyParamTag: 'Checks for empty @param tags within javadoc.',
	JavadocEmptyReturnTag: 'Checks for empty @return tags within javadoc.',
	JavadocEmptySeeTag: 'Checks for empty @see tags within javadoc.',
	JavadocEmptySinceTag: 'Checks for empty @since tags within javadoc.',
	JavadocEmptyThrowsTag: 'Checks for empty @throws tag within javadoc',
	JavadocEmptyVersionTag: 'Checks for empty @version tags within javadoc.',
	JavadocMissingExceptionDescription: 'Checks for missing description within @exception javadoc tags.',
	JavadocMissingParamDescription: 'Checks for missing description within @param javadoc tags.',
	JavadocMissingThrowsDescription: 'Checks for missing description within @throws javadoc tags.',
	JdbcConnectionReference: 'Check for direct use of java.sql.Connection, which is discouraged and almost never necessary in application code.',
	JdbcResultSetReference: 'Check for direct use of java.sql.ResultSet, which is not necessary if using the Groovy Sql facility or an ORM framework such as Hibernate.',
	JdbcStatementReference: 'Check for direct use of java.sql.Statement, java.sql.PreparedStatement, or java.sql.CallableStatement, which is not necessary if using the Groovy Sql facility or an ORM framework such as Hibernate.',
	LineLength: 'Checks the maximum length for each line of source code. It checks for number of characters, so lines that include tabs may appear longer than the allowed number when viewing the file. The maximum line length can be configured by setting the length property, which defaults to 120.',
	LocaleSetDefault: 'Checks for calls to Locale.setDefault(), which sets the Locale across the entire JVM.',
	LoggerForDifferentClass: 'Checks for instantiating a logger (Log4J, SLF4J, Logback, Apache Commons Logging or Java Util Logging) for a class other than the current class.',
	LoggerWithWrongModifiers: 'Logger objects should be declared private, static and final. If subclasses should have access to a Logger in a parent class then the Logger should be declared protected, non-static and final. This rule find loggers that are not declared with these modifiers.',
	LoggingSwallowsStacktrace: 'If you are logging an exception then the proper API is to call error(Object, Throwable), which will log the message and the exception stack trace. If you call error(Object) then the stacktrace may not be logged.',
	LongLiteralWithLowerCaseL: 'In Java and Groovy, you can specify long literals with the L or l character, for instance 55L or 24l. It is best practice to always use an uppercase L and never a lowercase l. This is because 11l rendered in some fonts may look like 111 instead of 11L.',
	MethodCount: 'A class with too many methods is probably a good suspect for refactoring, in order to reduce its complexity and find a way to have more fine grained objects.The maxMethods property (30) specifies the threshold.',
	MethodName: 'Verifies that the name of each method matches a regular expression. By default it checks that the method name starts with a lowercase letter. The regex property specifies the regular expression to check the method name against. The ignoreMethodNames property (null) can specify method names that should be ignored, optionally containing wildcard characters (\'*\' or \'?\').',
	MethodParameterTypeRequired: 'Checks that method parameters are not dynamically typed, that is they are explicitly stated and different than def.',
	MethodReturnTypeRequired: 'Checks that method return types are not dynamic, that is they are explicitly stated and different than def.',
	MethodSize: 'Checks if the size of a method exceeds the number of lines specified by the maxLines property (100).',
	MisorderedStaticImports: 'Static imports should never be declared after nonstatic imports.',
	MissingBlankLineAfterImports: 'Makes sure there is a blank line after the imports of a source code file.',
	MissingBlankLineAfterPackage: 'Makes sure there is a blank line after the package statement of a source code file.',
	MissingNewInThrowStatement: 'A common Groovy mistake when throwing exceptions is to forget the new keyword. For instance, "throw RuntimeException()" instead of "throw new RuntimeException()". If the error path is not unit tested then the production system will throw a Method Missing exception and hide the root cause. This rule finds constructs like "throw RuntimeException()" that look like a new keyword was meant to be used but forgotten.',
	MissingOverrideAnnotation: 'Checks for methods that override a method in a super class or implement a method in an interface but are not annotated with @Override.',
	MultipleLoggers: 'This rule catches classes that have more than one logger object defined. Typically, a class has zero or one logger objects.',
	MultipleUnaryOperators: 'Checks for multiple consecutive unary operators. These are confusing, and are likely typos and bugs.',
	NestedBlockDepth: 'Checks for blocks or closures nested more than maxNestedBlockDepth (5) levels deep.',
	NestedForLoop: 'Reports classes with nested for loops.',
	NestedSynchronization: 'Nested synchronized statements should be avoided. Nested synchronized statements are either useless (if the lock objects are identical) or prone to deadlock.',
	NoDef: 'def should not be used. You should replace it with concrete type.',
	NoDouble: 'Checks for use of the double or Double types, in fields, variables, method parameters and method return types.',
	NoFloat: 'Checks for use of the float or Float types, in fields, variables, method parameters and method return types.',
	NoJavaUtilDate: 'Do not use java.util.Date. Prefer the classes in the java.time.* packages.',
	NoTabCharacter: 'Checks that all source files do not contain the tab character',
	NoWildcardImports: 'Wildcard imports, static or otherwise, should not be used.',
	NonFinalPublicField: 'Finds code that violates secure coding principles for mobile code by declaring a member variable public but not final.',
	NonFinalSubclassOfSensitiveInterface: 'The permissions classes such as java.security.Permission and java.security.BasicPermission are designed to be extended. Classes that derive from these permissions classes, however, must prohibit extension. This prohibition ensures that malicious subclasses cannot change the properties of the derived class. Classes that implement sensitive interfaces such as java.security.PrivilegedAction and java.security.PrivilegedActionException must also be declared final for analogous reasons.',
	ObjectFinalize: 'The finalize() method should only be called by the JVM after the object has been garbage collected.',
	ObjectOverrideMisspelledMethodName: 'Verifies that the names of the most commonly overridden methods of Object: equals, hashCode and toString, are correct.',
	PackageName: 'Verifies that the package name for a class matches a regular expression. By default it checks that the package name consists of only lowercase letters, separated by periods. The regex property specifies the regular expression used to validate the package name. The packageNameRequired property indicates whether a package name declaration is required for all classes.',
	PackageNameMatchesFilePath: 'A package source file\'s path should match the package itself. To find the package-relevant subpath in the file path the groupId needs to be configured. It is expected in every package declaration.',
	ParameterCount: 'Checks if the number of parameters in method/constructor exceeds the number of parameters specified by the maxParameters property.',
	ParameterName: 'Verifies that the name of each parameter matches a regular expression. This rule applies to method parameters, constructor parameters and closure parameters. By default it checks that parameter names start with a lowercase letter and contains only letters or numbers. The regex property specifies the default regular expression used to validate the parameter name. The ignoreParameterNames property (null) can specify parameter names that should be ignored, optionally containing wildcard characters (\'*\' or \'?\').',
	ParameterReassignment: 'Checks for a method or closure parameter being reassigned to a new value within the body of the method/closure, which is a confusing and questionable practice. Use a temporary variable instead.',
	PrintStackTrace: 'Checks for calls to printStackTrace().',
	Println: 'Checks for calls to this.print(), this.println() or this.printf().',
	PrivateFieldCouldBeFinal: 'Checks for private fields that are only set within a constructor or field initializer. Such fields can safely be made final.',
	PropertyName: 'Verifies that the name of each property matches a regular expression. By default it checks that property names other than \'static final\' start with a lowercase letter and contains only letters or numbers, and \'static final\' property names start with an uppercase letter and contain only uppercase letters, numbers and underscores. The regex property specifies the default regular expression used to validate property names. The finalRegex property specifies the regular expression to validate \'final\' property names. The staticRegex property specifies the regular expression to validate \'static\' property names. The staticFinalRegex property specifies the regular expression to validate \'static final\' property names. The ignorePropertyNames property (null) can specify property names that should be ignored, optionally containing wildcard characters (\'*\' or \'?\').',
	PublicFinalizeMethod: 'Creates a violation when the program violates secure coding principles by declaring a finalize() method public.',
	PublicInstanceField: 'Using public fields is considered to be a bad design. Use properties instead.',
	PublicMethodsBeforeNonPublicMethods: 'Enforce that all public methods are above protected and private methods.',
	RandomDoubleCoercedToZero: 'The Math.random() method returns a double result greater than or equal to 0.0 and less than 1.0. If you coerce this result into an Integer or int, then it is coerced to zero. Casting the result to int, or assigning it to an int field is probably a bug.',
	RemoveAllOnSelf: 'Don\'t use removeAll to clear a collection. If you want to remove all elements from a collection c, use c.clear, not c.removeAll(c). Calling c.removeAll(c) to clear a collection is less clear, susceptible to errors from typos, less efficient and for some collections, might throw a ConcurrentModificationException.',
	RequiredRegex: 'Checks for a specified regular expression that must exist within the source code. The regex property specifies the regular expression to check for. It is required and cannot be null or empty.',
	RequiredString: 'Checks for a specified text string that must exist within the source code. The string property specifies the String to check for. It is required and cannot be null or empty.',
	ReturnFromFinallyBlock: 'Returning from a finally block is confusing and can hide the original exception.',
	ReturnNullFromCatchBlock: 'Returning null from a catch block often masks errors and requires the client to handle error codes. In some coding styles this is discouraged.',
	ReturnsNullInsteadOfEmptyArray: 'Consider returning a zero length array rather than null. It is often a better design to return a length zero array rather than a null reference to indicate that there are no results (i.e., an empty list of results). This way, no explicit check for null is needed by clients of the method.',
	ReturnsNullInsteadOfEmptyCollection: 'Consider returning a zero length collection rather than null. It is often a better design to return a length zero collection rather than a null reference to indicate that there are no results (i.e., an empty list of results). This way, no explicit check for null is needed by clients of the method.',
	SerialPersistentFields: 'To use a Serializable object\'s serialPersistentFields correctly, it must be declared private, static, and final.',
	SerialVersionUID: 'A serialVersionUID is normally intended to be used with Serialization. It needs to be of type long, static, and final. Also, it should have a visibility modifier such as public or private. Providing no modifier creates a Property and Groovy generates a getter, which is probably not intended.',
	SerializableClassMustDefineSerialVersionUID: 'Classes that implement Serializable should define a serialVersionUID. If you don\'t define serialVersionUID, the system will make one by hashing most of your class\'s features. Then if you change anything, the UID will change and Java won\'t let you reload old data.',
	SimpleDateFormatMissingLocale: 'Be sure to specify a Locale when creating a new instance of SimpleDateFormat; the class is locale-sensitive. If you instantiate SimpleDateFormat without a Locale parameter, it will format the date and time according to the default Locale. Both the pattern and the Locale determine the format. For the same pattern, SimpleDateFormat may format a date and time differently if the Locale varies.',
	SpaceAfterCatch: 'Check that there is exactly one space (blank) after the catch keyword and before the opening parenthesis.',
	SpaceAfterClosingBrace: 'Check that there is at least one space (blank) or whitespace after each closing brace ("}") for method/class/interface declarations, closure expressions and block statements.',
	SpaceAfterComma: 'Checks that there is at least one space or whitespace following each comma. That includes checks for method and closure declaration parameter lists, method call parameter lists, Map literals and List literals.',
	SpaceAfterFor: 'Check that there is exactly one space (blank) after the for keyword and before the opening parenthesis.',
	SpaceAfterIf: 'Check that there is exactly one space (blank) after the if keyword and before the opening parenthesis.',
	SpaceAfterOpeningBrace: 'Check that there is at least one space (blank) or whitespace after each opening brace ("{") for method/class/interface declarations, closure expressions and block statements.',
	SpaceAfterSemicolon: 'Checks that there is at least one space or whitespace following each semicolon separating multiple statements on a single line or the clauses within a classic for loop.',
	SpaceAfterSwitch: 'Check that there is exactly one space (blank) after the switch keyword and before the opening parenthesis.',
	SpaceAfterWhile: 'Check that there is exactly one space (blank) after the while keyword and before the opening parenthesis.',
	SpaceAroundClosureArrow: 'Checks that there is whitespace around the closure arrow (->) symbol',
	SpaceAroundMapEntryColon: 'Check for configured formatting of whitespace around colons for literal Map entries. The characterBeforeColonRegex and characterAfterColonRegex properties specify a regular expression that must match the character before/after the colon.',
	SpaceAroundOperator: 'Check that there is at least one space (blank) or whitespace around each binary operator.',
	SpaceBeforeClosingBrace: 'Check that there is at least one space (blank) or whitespace before each closing brace ("}") for method/class/interface declarations, closure expressions and block statements.',
	SpaceBeforeOpeningBrace: 'Check that there is at least one space (blank) or whitespace before each opening brace ("{") for method/class/interface declarations, closure expressions and block statements.',
	SpockIgnoreRestUsed: 'If Spock\'s @IgnoreRest appears on any method, all non-annotated test methods are not executed. This behaviour is almost always unintended. It\'s fine to use @IgnoreRest locally during development, but when committing code, it should be removed.',
	StatelessClass: 'Checks for fields on classes that should remain "stateless" and reentrant. The ignoreFieldNames property (null) specifies one or more field names that should be ignored. The ignoreFieldTypes property specifies one or more field type names that should be ignored. Both can optionally contain wildcard characters (\'*\' or \'?\').',
	StatelessSingleton: 'There is no point in creating a stateless Singleton because there is nothing within the class that needs guarding and no side effects to calling the constructor. Just create new instances of the object or write a Utility class with static methods.',
	StaticCalendarField: 'Calendar objects should not be used as static fields. Calendars are inherently unsafe for multihtreaded use. Sharing a single instance across thread boundaries without proper synchronization will result in erratic behavior of the application.',
	StaticConnection: 'Creates violations when a java.sql.Connection object is used as a static field. Database connections stored in static fields will be shared between threads, which is unsafe and can lead to race conditions.',
	StaticDateFormatField: 'DateFormat objects should not be used as static fields. DateFormat are inherently unsafe for multithreaded use. Sharing a single instance across thread boundaries without proper synchronization will result in erratic behavior of the application.',
	StaticFieldsBeforeInstanceFields: 'Enforce that all static fields are above all instance fields within a class',
	StaticMatcherField: 'Matcher objects should not be used as static fields. Matcher instances are inherently unsafe for multithreaded use. Sharing a single instance across thread boundaries without proper synchronization will result in erratic behavior of the application.',
	StaticMethodsBeforeInstanceMethods: 'Enforce that all static methods are above all instance methods within a class',
	StaticSimpleDateFormatField: 'SimpleDateFormat objects should not be used as static fields. SimpleDateFormat are inherently unsafe for multi-threaded use. Sharing a single instance across thread boundaries without proper synchronization will result in erratic behavior of the application.',
	SwallowThreadDeath: 'Checks for code that catches ThreadDeath without re-throwing it.',
	SynchronizedMethod: 'This rule reports uses of the synchronized keyword on methods. Synchronized methods are the same as synchronizing on \'this\', which effectively make your synchronization policy public and modifiable by other objects. To avoid possibilities of deadlock, it is better to synchronize on internal objects.',
	SynchronizedOnBoxedPrimitive: 'The code synchronizes on a boxed primitive constant, such as an Integer. Since Integer objects can be cached and shared, this code could be synchronizing on the same object as other, unrelated code, leading to unresponsiveness and possible deadlock',
	SynchronizedOnGetClass: 'Synchronization on getClass rather than class literal. This instance method synchronizes on this.getClass(). If this class is subclassed, subclasses will synchronize on the class object for the subclass, which isn\'t likely what was intended.',
	SynchronizedOnReentrantLock: 'Synchronizing on a ReentrantLock field is almost never the intended usage. A ReentrantLock should be obtained using the lock() method and released in a finally block using the unlock() method.',
	SynchronizedOnString: 'Synchronization on a String field can lead to deadlock because Strings are interned by the JVM and can be shared.',
	SynchronizedOnThis: 'This rule reports uses of the synchronized blocks where the synchronization reference is \'this\'. Doing this effectively makes your synchronization policy public and modifiable by other objects. To avoid possibilities of deadlock, it is better to synchronize on internal objects.',
	SynchronizedReadObjectMethod: 'Catches Serializable classes that define a synchronized readObject method. By definition, an object created by deserialization is only reachable by one thread, and thus there is no need for readObject() to be synchronized. If the readObject() method itself is causing the object to become visible to another thread, that is an example of very dubious coding style.',
	SystemErrPrint: 'Checks for calls to System.err.print(), System.err.println() or System.err.printf().',
	SystemExit: 'Web applications should never call System.exit(). A call to System.exit() is probably part of leftover debug code or code imported from a non-J2EE application.',
	SystemOutPrint: 'Checks for calls to System.out.print(), System.out.println() or System.out.printf().',
	SystemRunFinalizersOnExit: 'Method calls to System.runFinalizersOnExit() should not be allowed. This method is inherently non-thread-safe, may result in data corruption, deadlock, and may effect parts of the program far removed from it\'s call point. It is deprecated, and it\'s use strongly discouraged.',
	TernaryCouldBeElvis: 'Checks for ternary expressions where the boolean and true expressions are the same. These can be simplified to an Elvis expression.',
	ThisReferenceEscapesConstructor: 'Reports constructors passing the \'this\' reference to other methods. This equals exposing a half-baked objects and can lead to race conditions during initialization. For reference, see Java Concurrency Gotchas by Alex Miller and Java theory and practice: Safe construction techniques by Brian Goetz.',
	ThreadLocalNotStaticFinal: 'ThreadLocal fields should be static and final. In the most common case a java.lang.ThreadLocal instance associates state with a thread. A non-static non-final java.lang.ThreadLocal field associates state with an instance-thread combination. This is seldom necessary and often a bug which can cause memory leaks and possibly incorrect behavior.',
	ThreadYield: 'Method calls to Thread.yield() should not be allowed. This method has no useful guaranteed semantics, and is often used by inexperienced programmers to mask race conditions.',
	ThrowError: 'Checks for throwing an instance of java.lang.Error.',
	ThrowException: 'Checks for throwing an instance of java.lang.Exception.',
	ThrowExceptionFromFinallyBlock: 'Throwing an exception from a finally block is confusing and can hide the original exception.',
	ThrowNullPointerException: 'Checks for throwing an instance of java.lang.NullPointerException.',
	ThrowRuntimeException: 'Checks for throwing an instance of java.lang.RuntimeException.',
	ThrowThrowable: 'Checks for throwing an instance of java.lang.Throwable.',
	ToStringReturnsNull: 'Checks for toString() methods that return null.',
	TrailingComma: 'Check whether list and map literals contain optional trailing comma.',
	TrailingWhitespace: 'Checks that no lines of source code end with whitespace characters.',
	UnnecessaryBigDecimalInstantiation: 'It is unnecessary to instantiate BigDecimal objects. Instead just use the decimal literal or the \'G\' identifier to force the type, such as 123.45 or 123.45G.',
	UnnecessaryBigIntegerInstantiation: 'It is unnecessary to instantiate BigInteger objects. Instead just use the literal with the \'G\' identifier to force the type, such as 8G or 42G.',
	UnnecessaryBooleanExpression: 'Checks for unnecessary boolean expressions, including ANDing (&&) or ORing (||) with true, false, null, or a Map/List/String/Number literal. Also checks for negation (!) of true, false, null, or a Map/List/String/Number literal.',
	UnnecessaryBooleanInstantiation: 'Use Boolean.valueOf() for variable values or Boolean.TRUE and Boolean.FALSE for constant values instead of calling the Boolean() constructor directly or calling Boolean.valueOf(true) or Boolean.valueOf(false).',
	UnnecessaryCallForLastElement: 'This rule checks for excessively verbose methods of accessing the last element of an array or list. For instance, it is possible to access the last element of an array by performing array[array.length - 1], in Groovy it is simpler to either call array.last() or array[-1]. The same is true for lists. This violation is triggered whenever a get, getAt, or array-style access is used with an object size check.',
	UnnecessaryCallToSubstring: 'Calling String.substring(0) always returns the original string. This code is meaningless.',
	UnnecessaryCast: 'Checks for unnecessary cast operations',
	UnnecessaryCatchBlock: 'Violations are triggered when a catch block does nothing but throw the original exception. In this scenario there is usually no need for a catch block, just let the exception be thrown from the original code. This condition frequently occurs when catching an exception for debugging purposes but then forgetting to take the catch statement out.',
	UnnecessaryCollectCall: 'Some method calls to Object.collect(Closure) can be replaced with the spread operator. For instance, list.collect { it.multiply(2) } can be replaced by list*.multiply(2). Warning: if a collection is null, collect will return an empty list, while *. will return null.',
	UnnecessaryCollectionCall: 'Useless call to collections. This call doesn\'t make sense. For any collection c, calling c.containsAll(c) should always be true, and c.retainAll(c) should have no effect.',
	UnnecessaryConstructor: 'This rule detects when a constructor is not necessary; i.e., when there\'s only one constructor, it\'s public, has an empty body, and takes no arguments.',
	UnnecessaryDefInFieldDeclaration: 'If a field has a visibility modifier or a type declaration, then the def keyword is unneeded. For instance, \'static def constraints = {}\' is redundant and can be simplified to \'static constraints = {}.',
	UnnecessaryDefInMethodDeclaration: 'If a method has a visibility modifier or a type declaration, then the def keyword is unneeded. For instance \'def private method() {}\' is redundant and can be simplified to \'private method() {}\'.',
	UnnecessaryDefInVariableDeclaration: 'If a variable has a visibility modifier or a type declaration, then the def keyword is unneeded. For instance \'def private n = 2\' is redundant and can be simplified to \'private n = 2\'.',
	UnnecessaryDotClass: 'To make a reference to a class, it is unnecessary to specify the \'.class\' identifier. For instance String.class can be shortened to String.',
	UnnecessaryDoubleInstantiation: 'It is unnecessary to instantiate Double objects. Instead just use the double literal or the \'D\' identifier to force the type, such as 123.45d or 0.42d.',
	UnnecessaryElseStatement: 'When an if statement block ends with a return statement the else is unnecessary. The logic in the else branch can be run without being in a new scope.',
	UnnecessaryFail: 'In a unit test, catching an exception and immediately calling Assert.fail() is pointless and hides the stack trace. It is better to rethrow the exception or not catch the exception at all.',
	UnnecessaryFinalOnPrivateMethod: 'A private method is marked final. Private methods cannot be overridden, so marking it final is unnecessary.',
	UnnecessaryFloatInstantiation: 'It is unnecessary to instantiate Float objects. Instead just use the float literal with the \'F\' identifier to force the type, such as 123.45F or 0.42f.',
	UnnecessaryGString: 'String objects should be created with single quotes, and GString objects created with double quotes. Creating normal String objects with double quotes is confusing to readers.',
	UnnecessaryGetter: 'Checks for explicit calls to getter/accessor methods which can, for the most part, be replaced by property access. A getter is defined as a method call that matches get[A-Z] but not getClass() or get[A-Z][A-Z] such as getURL(). Getters do not take method arguments. The ignoreMethodNames property (null) can specify method names that should be ignored, optionally containing wildcard characters (\'*\' or \'?\').',
	UnnecessaryGroovyImport: 'A Groovy file does not need to include an import for classes from java.lang, java.util, java.io, java.net, groovy.lang and groovy.util, as well as the classes java.math.BigDecimal and java.math.BigInteger.',
	UnnecessaryIfStatement: 'Checks for if statements where the if and else blocks (or subsequent fall-through to a return) are merely returning true and false constants. These cases can be replaced by a simple return statement.',
	UnnecessaryInstanceOfCheck: 'This rule finds instanceof checks that cannot possibly evaluate to true. For instance, checking that (!variable instanceof String) will never be true because the result of a not expression is always a boolean.',
	UnnecessaryInstantiationToGetClass: 'Avoid instantiating an object just to call getClass() on it; use the .class public member instead.',
	UnnecessaryIntegerInstantiation: 'It is unnecessary to instantiate Integer objects. Instead just use the literal with the \'I\' identifier to force the type, such as 8I or 42i.',
	UnnecessaryLongInstantiation: 'It is unnecessary to instantiate Long objects. Instead just use the literal with the \'L\' identifier to force the type, such as 8L or 42L.',
	UnnecessaryModOne: 'Any expression mod 1 (exp % 1) is guaranteed to always return zero. This code is probably an error, and should be either (exp & 1) or (exp % 2).',
	UnnecessaryNullCheck: 'Groovy contains the safe dereference operator, which can be used in boolean conditional statements to safely replace explicit "x == null" tests.',
	UnnecessaryNullCheckBeforeInstanceOf: 'There is no need to check for null before an instanceof; the instanceof keyword returns false when given a null argument.',
	UnnecessaryObjectReferences: 'Violations are triggered when an excessive set of consecutive statements all reference the same variable. This can be made more readable by using a with or identity block.',
	UnnecessaryOverridingMethod: 'The overriding method merely calls the same method defined in a superclass',
	UnnecessaryPackageReference: 'Checks for explicit package reference for classes that Groovy imports by default, such as java.lang.String, java.util.Map and groovy.lang.Closure.',
	UnnecessaryParenthesesForMethodCallWithClosure: 'If a method is called and the only parameter to that method is an inline closure then the parentheses of the method call can be omitted.',
	UnnecessaryPublicModifier: 'The \'public\' modifier is not required on methods or classes.',
	UnnecessaryReturnKeyword: 'In Groovy, the return keyword is often optional. If a statement is the last line in a method or closure then you do not need to have the return keyword.',
	UnnecessarySafeNavigationOperator: 'Check for the safe navigation operator (?.) applied to constants and literals, which can never be null.',
	UnnecessarySelfAssignment: 'Method contains a pointless self-assignment to a variable or property.',
	UnnecessarySemicolon: 'Semicolons as line terminators are not required in Groovy: remove them. Do not use a semicolon as a replacement for empty braces on for and while loops; this is a confusing practice.',
	UnnecessarySetter: 'Checks for explicit calls to setter methods which can, for the most part, be replaced by assignment to property. A setter is defined as a method call that matches set[A-Z] but not set[A-Z][A-Z] such as setURL(). Setters take one method argument.',
	UnnecessaryStringInstantiation: 'Use a String literal (e.g., "...") instead of calling the corresponding String constructor (new String("..")) directly.',
	UnnecessaryTernaryExpression: 'Checks for ternary expressions where the conditional expression always evaluates to a boolean and the true and false expressions are merely returning true and false constants. Also checks for ternary expressions where both expressions are the same constant or variable.',
	UnnecessaryToString: 'Checks for unnecessary calls to toString().',
	UnnecessaryTransientModifier: 'The field is marked as transient, but the class isn\'t Serializable, so marking it as transient has no effect.',
	UnsafeArrayDeclaration: 'Triggers a violation when an array is declared public, final, and static. Secure coding principles state that, in most cases, an array declared public, final and static is a bug because arrays are mutable objects.',
	UnsafeImplementationAsMap: 'Reports incomplete interface implementations created by map-to-interface coercions. Example: [hasNext: { ... }] as Iterator (Not all Iterator methods are implemented. An UnsupportedOperationException will be thrown upon call to e.g. next().) By default, this rule does not apply to test files.',
	UnusedArray: 'Checks for array allocations that are not assigned or used, unless it is the last statement within a block.',
	UnusedImport: 'Imports for a class that is never referenced within the source file is unnecessary.',
	UnusedMethodParameter: 'This rule finds instances of method parameters not being used. It does not analyze private methods (that is done by the UnusedPrivateMethodParameter rule) or methods marked @Override.',
	UnusedObject: 'Checks for object allocations that are not assigned or used, unless it is the last statement within a block',
	UnusedPrivateField: 'Checks for private fields that are not referenced within the same class.',
	UnusedPrivateMethod: 'Checks for private methods that are not referenced within the same class.',
	UnusedPrivateMethodParameter: 'Checks for parameters to private methods that are not referenced within the method body.',
	UnusedVariable: 'Checks for variables that are never referenced. The ignoreVariableNames property (null) specifies one or more variable names that should be ignored, optionally containing wildcard characters (\'*\' or \'?\').',
	UseAssertEqualsInsteadOfAssertTrue: 'This rule detects JUnit assertions in object equality. These assertions should be made by more specific methods, like assertEquals.',
	UseAssertFalseInsteadOfNegation: 'In unit tests, if a condition is expected to be false then there is no sense using assertTrue with the negation operator. For instance, assertTrue(!condition) can always be simplified to assertFalse(condition)',
	UseAssertNullInsteadOfAssertEquals: 'This rule detects JUnit calling assertEquals where the first or second parameter is null. These assertion should be made against the assertNull method instead.',
	UseAssertSameInsteadOfAssertTrue: 'This rule detects JUnit calling assertTrue where the first or second parameter is an Object#is() call testing for reference equality. These assertion should be made against the assertSame method instead.',
	UseAssertTrueInsteadOfAssertEquals: 'This rule detects JUnit calling assertEquals where the first parameter is a boolean. These assertions should be made by more specific methods, like assertTrue or assertFalse.',
	UseAssertTrueInsteadOfNegation: 'In unit tests, if a condition is expected to be true then there is no sense using assertFalse with the negation operator. For instance, assertFalse(!condition) can always be simplified to assertTrue(condition)',
	UseCollectMany: 'In many case collectMany() yields the same result as collect{}.flatten(). It is easier to understand and more clearly conveys the intent.',
	UseCollectNested: 'Instead of nested collect{}-calls use collectNested{}',
	UseOfNotifyMethod: 'This code calls notify() rather than notifyAll(). Java monitors are often used for multiple conditions. Calling notify() only wakes up one thread, meaning that the thread woken up might not be the one waiting for the condition that the caller just satisfied.',
	VariableName: 'Verifies that the name of each method matches a regular expression. By default it checks that non-\'final\' variable names start with a lowercase letter and contains only letters or numbers, and \'final\' variable names start with an uppercase letter and contain only uppercase letters, numbers and underscores. The regex property specifies the default regular expression used to validate a non-\'final\' variable name. The finalRegex property specifies the regular expression used to validate \'final\' variable names. The ignoreVariableNames property (null) can specify variable names that should be ignored, optionally containing wildcard characters (\'*\' or \'?\').',
	VariableTypeRequired: 'Checks that variable types are explicitly specified in declarations (and not using def)',
	VectorIsObsolete: 'The java.util.Vector class is effectively obsolete. Use the Java Collections Framework classes instead, including ArrayList or Collections.synchronizedList(). See the JDK javadoc.',
	VolatileArrayField: 'Volatile array fields are unsafe because the contents of the array are not treated as volatile. Changing the entire array reference is visible to other threads, but changing an array element is not.',
	VolatileLongOrDoubleField: 'Long or double fields should not be declared as volatile. Java specifies that reads and writes from such fields are atomic, but many JVM\'s have violated this specification. Unless you are certain of your JVM, it is better to synchronize access to such fields rather than declare them volatile. This rule flags fields marked volatile when their type is double or long or the name of their type is "Double" or "Long".',
	WaitOutsideOfWhileLoop: 'Calls to Object.wait() must be within a while loop. Consider using the Java concurrency utilities instead of wait() and notify().',
	WhileStatementBraces: 'Use braces for while statements, even for a single statement.'
]

if (args.length == 0) {
    println 'After generating text result from codenarc (adding reportFormat("text") in build.gradle codenarc config), and using ./gradlew check'
    println 'Please use this script like : groovy codenarcTextResultParse.groovy path/to/the/file/to/parse.txt'
    return
}


String fileContent = new File(args[0]).text

def rulesOccurence = [:]

rules.each {
    // count number of occurence
    rulesOccurence."$it.key - $it.value" = fileContent.count("Rule=$it.key")
}

rulesOccurence.sort { -it.value }.each {
    if(it.value) println "$it.value : $it.key"
}
