////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Setup Edit Product Store
The Product Store screen is used to manage a store with has all the information needed to sell products.

For example shippings ,a series of catalogs, which are composed of product categories and products,
 and also used to configure the payment processing settings , fulfillment, notification, promotions, payment processing,
 and tax calculation policies , and etc.

== How do I create a Product Store?
. Select the 'Product Store' sub menu and the screen will be displayed
. Enter the 'Product Store Id' field +
  (NOTE: If you do not enter the 'Product Store Id' field it will be used the default as 'Organization Party Id')
. Enter the 'Store Name' field
. Press the 'Update' button

== How do I update a Product Store?
Not all the fields on the Product Store can be updated. +
For example Product Store Id cannot be updated.
If these fields need to be amended then the Product Store will need to be removed and then re-created.

. Select the 'Product Store' sub menu and the screen will be displayed:
   Any existing Product Store will be displayed in the 'Items' box
. Amend the details in the line item that needs to be updated (eg Store Name)
. Press the 'Update' button displayed at the end of the line item that has been updated
