////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Setup Create First Customer
The First Customer screen provides +
 - create/edit the first customer of your organization +
 - and also setup the "Shipping Destination Address" , "General Correspondence Address", any telephone numbers,
 and email addresses you want for your first customer.

== How do I update the profile information of the first customer?
After the first customer is created the profile and contact information screen will be displayed

. Select the 'Update' button on the top corner of the profile information and the screen will be displayed:
  Any existing information will be displayed in the box
. Amend the details in the profile information that needs to be updated
. Press the 'Save' button
. Press the 'Cancel/Done' button for go back to the first customer screen
