////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Setup Edit First Product Category
The Edit First Product Category screen is used to manage the first category with related the first catalog.

== How do I create a Category?
. Select the 'Category' sub menu and the screen will be displayed
. Enter the 'Product Category Id ' field +
  (NOTE: If you do not enter the 'Product Category Id' field it will be used the default as 'Organization Party Id')
. Enter the 'Category Name' field
. Enter a description describing what the category is
. Press the 'Update' button

== How do I update a Category?
. Not all the fields on the Category can be updated. +
  For example Prod Catalog Id cannot be updated. +
  If these fields need to be amended then the Category will need to be removed and then re-created.
. Select the 'Category' sub menu and the screen will be displayed: Any existing Category will be displayed in the box
. Amend the details in the line item that needs to be updated (eg Category Name, Product Description )
. Press the 'Update' button displayed at the end of the line item that has been updated
