////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for import contact list parties
This is the initial screen to find an existing parties and select them for import to the contact list.

== Find selection fields.
* Party Id : The unique id of the party
* Party Type Id : The type of the party
* Role Type : The role of the party
* Contact Mech Type Id : the contact type according to the contact meth type's ID of the contact list. +
  There is a sub form for this field according to the contact mech type's ID.

== Import the parties
1. Select the parties in the search result list.
2. Press the "Submit Query" button