////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Edit a contact list.
This screen enables you to edit an existing contactlist or create a new one.
Below an explanation of the fields

== Contact list fields.
* ContactList Id   : The unique id of the contact list
* ContactList Name : The name of the contactlist
* ContactList Type : The type of the contactlist
* Is Public ?      :
* Is Single Use ?  : If set to 'Y' all parties of this contactlist will be deleted after sending the email.
* Contact Mech type: the contact type like email, postal address etc.
* Marketing Campaign Name : The marketing campaign name
* Owner Party Id:
* Verify Email From:
* Verify Email Screen:
* Verify Email Subject:
* Verify Email WebSite Id:
* Opt Out Screen: