////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Marketing Contact Lists.

A contactlist is currently an email mailing list to inform a certain number of parties via email. +
The system however already has a provision to use this facility for calling list or to  create mail and merge list
for paper documents.

== Contact Lists management in UI
include::HELP_FindContactLists.adoc[leveloffset=+2]

include::HELP_EditContactList.adoc[leveloffset=+2]

include::HELP_ImportContactListParties.adoc[leveloffset=+2]

