
<h1>${uiLabelMap.BusinessIntelligenceIntegratedFramework}</h1>
<p>
    ${uiLabelMap.BusinessIntelligenceNote1}
    ${uiLabelMap.BusinessIntelligenceNote2}
    ${uiLabelMap.BusinessIntelligenceNote3}
    ${uiLabelMap.BusinessIntelligenceNote4}
    ${uiLabelMap.BusinessIntelligenceNote5}
    ${uiLabelMap.BusinessIntelligenceNote6}
    ${uiLabelMap.BusinessIntelligenceNote7}
    ${uiLabelMap.BusinessIntelligenceNote8}
    ${uiLabelMap.BusinessIntelligenceNote9}
    ${uiLabelMap.BusinessIntelligenceNote10}
    ${uiLabelMap.BusinessIntelligenceNote11}
    ${uiLabelMap.BusinessIntelligenceNote12}
</p>
<h2>${uiLabelMap.BusinessIntelligenceCurrentStatus}</h2>
<p>
    ${uiLabelMap.BusinessIntelligenceNote13}
    ${uiLabelMap.BusinessIntelligenceNote14}
    ${uiLabelMap.BusinessIntelligenceNote15}
    ${uiLabelMap.BusinessIntelligenceNote16}
    ${uiLabelMap.BusinessIntelligenceNote17}
    ${uiLabelMap.BusinessIntelligenceNote18}
</p>
<h2>${uiLabelMap.BusinessIntelligenceQuickStartGuide}</h2>
<p>
    ${uiLabelMap.BusinessIntelligenceNote19}
    ${uiLabelMap.BusinessIntelligenceNote20}
    ${uiLabelMap.BusinessIntelligenceNote21}
    ${uiLabelMap.BusinessIntelligenceNote22}
    ${uiLabelMap.BusinessIntelligenceNote23}
    ${uiLabelMap.BusinessIntelligenceNote24}
    ${uiLabelMap.BusinessIntelligenceNote25}
    ${uiLabelMap.BusinessIntelligenceNote26}
    ${uiLabelMap.BusinessIntelligenceNote27}
    ${uiLabelMap.BusinessIntelligenceNote28}
</p>
