////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= SFA

Sale Force Automation component.

== Overview
The main purpose of the SFA application is to support the process of creating orders for leads.

The SFA application is for a specific user to list his leads, contacts accounts and opportunities. +
He can create new parties or he can assign existing parties to himself.

It is very much based on the party application as its source. +
Records from the party application are selected with only one basic reason: a possible sale in the future. +
That also means that records in the party manager should be complete, especially the role is pretty important.
Not All roles, but at least 'lead' 'contact' and 'Account' should be defined.

== SFA in User Interface

=== Main screen
The SFA main screen allows the quick create of any new lead and/or contact which is available on any SFA screen.
Further this screen is designed to provide an overview of this users activity.

=== SFA Accounts find/list screen
The Accounts screen will show you the list which you have created or which have been assigned to you.

=== SFA Contacts find/list screen
The Contact screen will show you the list which you have created.

=== SFA Leads find/list screen
The leads screen will show you the list which you have created or which have been assigned to you.

=== SFA SalesOpportunity find/list screen
The SalesOpportunity screen will show you the list which you have created.
