/*******************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *******************************************************************************/
/**
 * SecurityServerPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.ofbiz.crowd.security;

public interface SecurityServerPortType extends java.rmi.Remote {
    public com.atlassian.crowd.integration.soap.SOAPNestableGroup[] findAllGroupRelationships(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public com.atlassian.crowd.integration.soap.SOAPGroup addGroup(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, com.atlassian.crowd.integration.soap.SOAPGroup in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.InvalidGroupException;
    public void addPrincipalToRole(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public com.atlassian.crowd.integration.soap.SOAPPrincipal findPrincipalByToken(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.InvalidTokenException, java.rmi.RemoteException;
    public void updatePrincipalCredential(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, com.atlassian.crowd.integration.authentication.PasswordCredential in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.InvalidCredentialException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public java.lang.String[] getGrantedAuthorities(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public com.atlassian.crowd.integration.soap.SOAPPrincipal addPrincipal(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, com.atlassian.crowd.integration.soap.SOAPPrincipal in1, com.atlassian.crowd.integration.authentication.PasswordCredential in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.InvalidCredentialException, com.atlassian.crowd.integration.exception.InvalidPrincipalException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException;
    public void addAttributeToPrincipal(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, com.atlassian.crowd.integration.soap.SOAPAttribute in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public void invalidatePrincipalToken(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public java.lang.String[] findAllGroupNames(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public java.lang.String[] findRoleMemberships(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public void removePrincipal(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public boolean isValidPrincipalToken(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, com.atlassian.crowd.integration.authentication.ValidationFactor[] in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.ApplicationAccessDeniedException, java.rmi.RemoteException;
    public java.lang.String authenticatePrincipalSimple(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.InvalidAuthenticationException, com.atlassian.crowd.integration.exception.ApplicationAccessDeniedException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InactiveAccountException;
    public void removeRole(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public com.atlassian.crowd.integration.soap.SOAPCookieInfo getCookieInfo(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public void updatePrincipalAttribute(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, com.atlassian.crowd.integration.soap.SOAPAttribute in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public com.atlassian.crowd.integration.soap.SOAPGroup[] searchGroups(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, com.atlassian.crowd.integration.soap.SearchRestriction[] in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public long getCacheTime(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public boolean isRoleMember(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public void updateGroup(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2, boolean in3) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public java.lang.String[] findAllRoleNames(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public com.atlassian.crowd.integration.soap.SOAPRole findRoleByName(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public boolean isCacheEnabled(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public com.atlassian.crowd.integration.soap.SOAPGroup findGroupByName(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public void removePrincipalFromRole(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public java.lang.String authenticatePrincipal(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, com.atlassian.crowd.integration.authentication.PrincipalAuthenticationContext in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.InvalidAuthenticationException, com.atlassian.crowd.integration.exception.ApplicationAccessDeniedException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InactiveAccountException;
    public java.lang.String[] findGroupMemberships(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public void addPrincipalToGroup(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public void removeGroup(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public void removeAttributeFromPrincipal(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public java.lang.String[] findAllPrincipalNames(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public com.atlassian.crowd.integration.soap.SOAPRole addRole(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, com.atlassian.crowd.integration.soap.SOAPRole in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.InvalidRoleException;
    public java.lang.String createPrincipalToken(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, com.atlassian.crowd.integration.authentication.ValidationFactor[] in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.InvalidAuthenticationException, com.atlassian.crowd.integration.exception.ApplicationAccessDeniedException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InactiveAccountException;
    public com.atlassian.crowd.integration.soap.SOAPRole[] searchRoles(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, com.atlassian.crowd.integration.soap.SearchRestriction[] in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public void removePrincipalFromGroup(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public com.atlassian.crowd.integration.soap.SOAPPrincipal findPrincipalByName(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public void resetPrincipalCredential(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.InvalidCredentialException, java.rmi.RemoteException, com.atlassian.crowd.integration.exception.ApplicationPermissionException, com.atlassian.crowd.integration.exception.ObjectNotFoundException;
    public boolean isGroupMember(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public com.atlassian.crowd.integration.soap.SOAPPrincipal[] searchPrincipals(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0, com.atlassian.crowd.integration.soap.SearchRestriction[] in1) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public java.lang.String getDomain(com.atlassian.crowd.integration.authentication.AuthenticatedToken in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, java.rmi.RemoteException;
    public com.atlassian.crowd.integration.authentication.AuthenticatedToken authenticateApplication(com.atlassian.crowd.integration.authentication.ApplicationAuthenticationContext in0) throws java.rmi.RemoteException, com.atlassian.crowd.integration.exception.InvalidAuthorizationTokenException, com.atlassian.crowd.integration.exception.InvalidAuthenticationException, java.rmi.RemoteException;
}
