////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Payments.

Payments are transactions that received by or generated by a business.

They can be incoming or outgoing.

Incoming payments are normally from customers and outgoing ones to suppliers.

== Payments management in User Interface
include::HELP_findPayments.adoc[leveloffset=+2]

include::HELP_newPayment.adoc[leveloffset=+2]

include::HELP_paymentOverview.adoc[leveloffset=+2]

include::HELP_editPaymentApplications.adoc[leveloffset=+2]

include::HELP_editPayment.adoc[leveloffset=+2]

include::HELP_FindSalesInvoicesByDueDate.adoc[leveloffset=+2]

include::HELP_FindPurchaseInvoicesByDueDate.adoc[leveloffset=+2]
