////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= About Accounting

The Accounting system is organised according to generally accepted principles
such as double-entry accounting, a General Ledger with hierarchical accounts, 
journals and posting of transactions and corresponding entries.

The structure is primary based on the OMG GL standard and the work that was done 
on an AR/AP extension of the OMG GL standard. This correlates well with other
standards such as ebXML and OAGIS.

The Accounting entities are structured such that accounts for multiple
organisations can be managed. The multiple organisations could be multiple 
companies, or departments or other organisations within a company. Each
organisation can have various GL Accounts associated with it so that it can
operate with its own subset of the Master Chart of Accounts.

Each organisation can also have its own set of Journals for flexibility, even
though the use of Journals should be as minimal as possible in favour of allowing 
the system to automatically create and post transactions based on business events 
triggered by standard procedures and documents such as purchase and sales orders, 
invoices, inventory transfers, payments, receipts, and so on.

== Accounting Features

 * General Ledger
 * Accounts Receivable
 * Accounts Payable
 * Agreements 
 * Multi-currency Support
 * Billing Accounts
 * Fixed Asset Accounting

OFBiz accounting can be configured to handle multiple organisations including 
an unlimited number of companies, subsidiaries and departments.
