////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Organization GL Settings.

== Help for setting by domain

=== Help for Available Internal Organizations
The default screen shows a list of Party Groups that have the role of 'Internal Organization' associated with them.

If you have installed the demo data then the default company 'Company' as well as departments / business units and
 regional subsidiaries will be displayed.

For each 'Internal Organization' there is the ability to set the currency, fiscal periods and invoice prefixes.

include::HELP_PartyAcctgPreference.adoc[leveloffset=+2]

include::HELP_ListGlAccountOrganization.adoc[leveloffset=+2]

include::HELP_SetupGlJournals.adoc[leveloffset=+2]

include::HELP_GlAccountTypeDefaults.adoc[leveloffset=+2]

include::HELP_EditProductGlAccounts.adoc[leveloffset=+2]

include::HELP_EditProductCategoryGlAccounts.adoc[leveloffset=+2]

include::HELP_EditFinAccountTypeGlAccounts.adoc[leveloffset=+2]

include::HELP_GlAccountSalInvoice.adoc[leveloffset=+2]

include::HELP_GlAccountPurInvoice.adoc[leveloffset=+2]

include::HELP_GlAccountTypePaymentType.adoc[leveloffset=+2]

include::HELP_GlAccountNrPaymentMethod.adoc[leveloffset=+2]

include::HELP_EditVarianceReasonGlAccounts.adoc[leveloffset=+2]

include::HELP_EditCreditCardTypeGlAccounts.adoc[leveloffset=+2]

include::HELP_EditOrganizationTaxAuthorityGlAccounts.adoc[leveloffset=+2]

include::HELP_EditPartyGlAccount.adoc[leveloffset=+2]

include::HELP_TimePeriods.adoc[leveloffset=+2]
