////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Invoices.

Sales invoices are generated when customers buy something from your business.
You will need to provide a detailed list of the items bought and relevant taxes paid.
They are often referred to a 'tax invoices' as they contain information relating to the amount of sales tax (eg VAT / GST)
charged on the product or service.

Purchase invoices are generated by your suppliers when you order something from them. +
You may send them an order in the form of a Purchase Order. +
They will then send you the products and an invoice for payment. +
This invoice is the Purchase Invoice and it will contain details of the items bought plus any taxes. +

Both of these documents are used as proof to various tax authorities (eg Inland Revenue, Customs etc) that the required tax
has been charged or collected.

NOTE: The following is an extract from Ian McNulty's documentation work on accounting:

Invoices are created automatically by the system when certain criteria are met for each item on an order.
The criteria will vary depending on the type of product associated with the order item, and the type of order
(ie purchase/sales).

For Sales Orders that include digital goods, an invoice will be created when the order is placed, and that invoice will be
for all digital goods in the order. +
If there are non-digital or physical goods they will go in a separate invoice.

For Sales Orders that need physical fulfillment, an invoice will be created for all items in a shipment when the shipment
goes into the 'Packed' status.

For Purchase Orders an invoice will be created from a shipment when the shipment goes into the Received status.

== Invoices management in User Interface
include::HELP_findInvoices.adoc[leveloffset=+2]

include::HELP_invoiceOverview.adoc[leveloffset=+2]

include::HELP_editInvoice.adoc[leveloffset=+2]

include::HELP_newInvoice.adoc[leveloffset=+2]

include::HELP_editInvoiceApplications.adoc[leveloffset=+2]

include::HELP_listInvoiceItems.adoc[leveloffset=+2]

include::HELP_editInvoiceTimeEntries.adoc[leveloffset=+2]

include::HELP_sendPerEmail.adoc[leveloffset=+2]

include::HELP_invoiceRoles.adoc[leveloffset=+2]
