////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Agreements

An “agreement” is a way of recording a business arrangement or contract that your
business makes with other companies or individuals. Some common examples of
 agreements include Payment Terms (where you allow a customer up to 30
days to pay you) or Prompt Payment Discounts (where you offer a reduction on the
amount owing if your customer pays you before a certain date)

At the time of writing, OFBiz allows you to create the following type of agreements

 * Product
 * Purchase
 * Sales
 * Employee
 * Commission
 * End User Licence

The most common agreements you will use will be Sales Agreements (for your 
Customers), Purchase Agreements (for your Suppliers) and Commission Agreements 
(for your Sales Representatives).

== Sales Agreement

A “Sales Agreement” is an agreement between you and your customers. A customer
can also be another business. You can create a range of conditions for your 
customer including giving them such as payment discounts or special payment terms
and credit limits. 

If you have installed OFBiz with the demo data then there are already examples
of Sales Agreements created for you.

== Purchase Agreement

A “Purchase Agreement” is an agreement between your business and a supplier. You 
may have negotiated special conditions such as delivery, volume pricing and
invoice terms. 

If you have installed OFBiz with the demo data then there are already examples
of Purchase Agreements created for you.

== Commission Agreement

A “Commission Agreement” is an agreement that is used to calculate how much money
a Sales Representative will get when products they have promoted or marketed are 
sold to customers. The rate paid to the Sales Representative is can be based on a
fixed or variable on a percentage of each sale they make. These amounts can be 
quite small amounts so it can be easier to consolidate multiple commission 
payments into one large payment that is paid monthly.

If you have installed OFBiz with the demo data then there are already two example
Commission Agreements created for you.
