////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Agreements Item Promotions
This screen is used to enter or maintain any promotions that are associated with the Agreement Item.
This can be useful if you want to limit where a particular promotion is applied.
Promotions are setup in Catalog Manager and can be selected here.

== How do I add a promotion to an agreement item?
. Press the 'Add New Promotion' button
. The 'Edit Agreement Promo Applications' screen is displayed
. Select the 'Product Promo Id' from the drop down box
. Enter the 'From Date'
. Enter the 'Thru Date' if required (NOTE:This can be left blank)
. Enter the 'Sequence Num' if required
. Press the 'Submit' button

== How do I edit an existing promotion for an agreement item?
. Select the agreement item promotion by clicking on on the promotion id
. The 'Edit Agreement Promo Applications' screen is displayed
. Update the details required
. Press the 'Submit' button


== How do I delete a promotion from an agreement item?
. Press the 'Remove' button on the entry that needs to be deleted.
