////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Agreement Content
This screen use for uploading any contents that concern the agreement.
The screen consists of :

* Add Agreement Content
* Agreement Content List

== Add Agreement Content
To upload the content.
The content can be classified by choosing the Content Type Id and Mime Type Id.

== Agreement Content List
To Show the list of contents.
There are 2 buttons in each content:

. Download : To download the uploaded content
. Delete : To delete the uploaded content
