////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Find Invoices
The default screen is for the Invoices tab is 'Find Invoices'. It is used to locate existing invoices that have been created
automatically by the system or manually by the user.
It can also be used to create a new Sales or Purchase Invoice.

== How do I view all invoices?
. Press the 'Search' button to view all invoices

== How do I locate an existing invoice?
. Enter the 'Invoice ID' if known
. Enter a word from the invoice description in the 'Description' field if known
. Enter the 'Invoice Type' if known
. Enter the 'From Party Id' if known +
  (NOTE: In most cases for a Sales Invoices this will be Company. For Purchase Invoice it will be the supplier party id)
. Enter the 'Billing Account Id' if known
. Enter the invoice status in the 'Status Id' field if known
. Enter the 'To Party Id' if known +
  (NOTE: In most cases for a Purchase Invoice this will be company. For Sales Invoices it will be the customer party id)
. Press the 'Search' button to view all invoices
. All invoices that meet the search criteria will be displayed.

== How do I update an invoice?
. Locate the invoice using the 'Find Invoices' screen
. Using the relevant sub menu make the required changes.

== How do I delete an invoice?
Invoices cannot be deleted through the user interface.
They can only be cancelled (eg if they have been entered or created by mistake).

NOTE: They can probably be deleted using Entity Data Maintenance in the Webtools menu but this is not recommended for 2 reasons: +
      1) It may cause data integrity problems. +
      2) In case of audit it would be a problem.
