////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Edit Tax Authority
The 'Edit Tax Authority' sub menu is the first of six sub menus used in the creation or update of a Tax Authority.
On the creation or update of a Tax Authority it is the default screen that is displayed.

It can be used for updating the basic details of a Tax Authority such as:

. Changing whether a tax id or code is required for an exemption
. Modifying the tax id or code format
. Updating where or not to include the tax calculation as part of the product price

NOTE: An example of the Tax Id is as follows: +
      \d{2}\-\d{7}|\d{3}\-\d{2}\-\d{4} which translates to 99-9999999 or 999-99-9999