////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Capture Transaction
This screen is used to input or 'capture' a payment against a Sales Order.

Unlike the authorise, this function will actually deduct the amount from eg a credit card and apply the payment
to a specific order.

It is likely that the before the payment is 'captured' in this screen, it would have been through an authorisation first.

NOTE: TO CHECK: Investigate how this links in with the Payment Gateway Configurations screens

== How do I capture a transaction?
. Enter the Order Id for the payment (eg Sales Order Id)
. Enter Order Payment Preference Id +
  (TO CHECK Unsure of what this is...a type of unique identifier perhaps?)
. Select the 'Payment Method Type'
. Select the 'Payment Type'
. Enter the 'Amount'
. Press the 'Capture' button

A transaction will be created and can be viewed via the 'Gateway Responses' screen.