////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Find Agreements
The default screen is for the Agreements tab is 'Find Agreements'. It is used to locate existing agreements that have been created.
The user has the option to

* use the 'Find' button to locate an existing agreement or
* create a new one by clicking on the 'Create Agreement' button.

== How do I locate an existing agreement?
. Enter search option details if known
. Press the 'Find' button <<PARTY,party>>
. A list of existing agreements will be displayed

== How do I create a new agreement?
. Press the 'Create Agreement' button
. The 'Edit Agreement' screen is displayed
. Enter the details required and press the 'Submit' button

== How do I cancel an agreement?
. Locate the agreement required
. Press the 'Cancel' button on the agreement entry that needs to be cancelled
