////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Edit Financial Account Roles.
The Financial Account Roles sub menu screen allows you specify a party and link them to a role for a particular financial account.

It can be used to add party roles eg 'Approver' or 'Administrator' for credit limits or updates to the account.
If an account belongs to a company then you may want to add a person as a 'Contact' for dealing with the account.

The roles can also be time bound.
This means that you can specify a start and end date for the party role.

== How do I add a Party Role to a Financial Account?
. Select the 'Roles' sub menu for the Financial Account
. Fill in the Party Id field by using the field lookup tool or by directly entering the party id (eg flexadmin)
. Select the role from the drop down list for the Role Type Id field (eg administrator)
. Enter the From Date field
. Enter if the Thru Date field (optional)
. Press the 'Add' button
