////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Edit Invoice Time Entries
he Time Entries screen displays any time logged against the invoice.
For example these time entries can be from employee or external supplier timesheets that are tracked within OFBiz.
It is used to track any individual work or billable hours against an invoice.

== How do I add a new time entry for an invoice?
Threre are two options

. Add time entry to a new invoice and add time entry to an existing invoice.
. Timesheet entries can be added to an existing invoice from Workeffort Manager.

== How do I update a time entry for an invoice?
WARNING: To CHECK if this can only be done via timesheets.

== How do I remove a time entry from an invoice?

WARNING: TO CHECK if this is done via timesheets 