////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Financial Account Edit Deposit Slip and member
This screen displays the details of a Payment Group and its transactions.
The Deposit Slip for the Payment Group can be printed if required and the Payment Group itself can be updated.

Details that can be updated include the name of the Payment Group itself and the addition, removal or update of transactions.

NOTE: Any changes to the Payment Group will be automatically updated to the Deposit Slip.

== How do I update a Deposit Slip?
. Select the Payment Group required
. Update the 'Payment Group Name' if required
. Use the lookup for 'Payment Id' to add new transactions to the Payment Group if required
. Use the 'Cancel' button next to a particular transaction to remove it from the Payment Group
. Press the 'Update' or 'Add' buttons as required
. Press the 'Print Deposit Slip' button

The Deposit Slip will be displayed with the latest details of the transactions for the Payment Group