////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Financial Account New Deposit Slip
This screen allows the user to create an Payment Group and the transactions associated with the Payment Group will generate
a deposit slip.

== How do I create a New Deposit Slip?
. Press the 'Find' button to list all the available transactions
. Select the transactions to include in the Payment Group by using the 'Select All' or the check box that corresponds to
  the transactions required
. Enter a 'Payment Group Name' if required (If none is entered then by default this will be 'Payment Group Name')
. Press the 'Create Batch' button
. A button to print the deposit slip will be displayed as well as the edit screen to make any further changes to the Payment Batch
