////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Financial Account Transactions List.

== How do I add transactions to a financial account?
An example of how to bring in an opening balance is shown below:

. Navigate to the the Financial Account Transactions sub menu
. Select 'Adjustment' in the Fin Account Trans Type Id field
. Leave the 'Party Id' field blank
. Fill in the 'Transaction Date' field
. Fill in the 'Entry Date' field (NOTE TO CHECK: Need to check exactly what this is - is it the date the transaction is entered
  or is it the date the transaction is processed?)
. Fill in the 'Amount' field with the transaction amount
  (Eg. In our case this is the opening balance such as 353.88 - dont think we need the $ sign)
. Leave the 'Payment Id' field blank
. Leave the 'Order Id' field blank
. Leave the 'Order Item Seq Id' field blank
. Leave the 'Reason Enum Id' field blank (NOTE TO CHECK: This could be useful in identifying transactions to a greater level of detail....)
. Fill in the 'Comments' field (Eg: Opening Balance from XYZ Statement)
. Press the 'Add' button and the transaction will be displayed at the bottom of the screen

NOTE: When you now view the Financial Account detail the 'Actual Balance' and 'Available Balance' fields will show
      the entered opening balance (eg 353.88)

== Other ways to add transactions to a financial account?
* By selecting financial account as a payment method for a customer
* By selecting financial account as a refund method for a customer
