////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Credit Card Type GL Accounts
The Credit Card Type / GL Account default is used to map different types of credit card to different general ledger accounts.

NOTE: This setup will affect one side of a journal entry only.

This type of mapping is useful if you need to track the amounts to be collected from different credit card agents.

The OFBiz demo data comes with some setup here

NOTE: TO CHECK The demo entries appear to be duplicated...has something changed in ENUM for defining
       each credit card type.....?????)

Examples are as follows:

* American Express
* Visa
* Mastercard
* Diners Club

== How do I add a Credit Card Type GL Account mapping?
There are 10 mappings that come as part of the OFBiz demo data but they do appear to be duplicated for some reason.

. Select the 'Card Type' from the drop down list
. Select the 'GL Account Id' to map it to from the drop down list
. Press the 'Add' button
. The new 'Credit Card / GL Account Id' mapping is displayed in the list at the bottom of the screen

== How do I update a Credit Card Type GL Account mapping?
. Select the 'Card Type' from the drop down list
. Select the updated 'GL Account Id' to map it to from the drop down list
. Press the 'Add' button
. The updated 'Credit Card Type / GL Account' mapping is displayed in the list at the bottom of the screen

NOTE: TO CHECK Used 'Visa' as an example to update and the 'CCT_VISA' was updated but the 'Visa' one was'nt.
      This is probably related to the duplication.

== How do I remove a Credit Card Type GL Account mapping?
. Press the 'Remove' button next to the entry that you want to delete
. The entry is removed from the list of entries displayed
