////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Invoice Overview
The Invoice Overview screen is used to display the summary of an invoice in a single view.
The screen is divided into sections that show various information related to the invoice (eg Roles, Status, Terms, Items, Payments Applied, etc).

The following options are currently available from this screen:

* Create New (Create a new invoice)
* Copy (Create a copy of the current invoice)
* PDF (View a PDF of the current invoice)
* PDF default currency +
  (NOTE TO CHECK: Need to see how this is different from just the PDF view......)
* Status to 'Approved' (Change the status of the current invoice to 'Approved)
* Status to 'Sent' (Change the status of the current invoice to 'Sent')
* Status to 'Ready' (Change the status of the current invoice to 'Ready'. +
  NOTE: This will create the relevant accounting transactions and post them to the general ledger)
* Status to 'Cancelled' (Change the status of the current invoice to 'Cancelled')
* Save as Template +
  (NOTE TO CHECK: Save the current invoice format as a template)
