////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Billing Account Roles
This sub menu allows parties with specific roles to be associated with to a Billing Account. +

It is used to specify which party should be billed for the billing account.

It can be used as follows:

* Simple billing account for a single party
* More complex billing account where multiple parties (eg company subsidiaries) charge invoices to the billing account
  but a different party (eg head office) will pay the account

== How do I add a party role to a billing account?
Select the 'Roles' sub menu

. Enter or use the lookup to select the 'Party Id'
. Select the 'Role Type Id' from the drop down box (eg Bill To Customer)
. Leave the 'From Date' blank +
  (NOTE: If left blank it will default to the current date and time)
. Leave the 'Thru Date' blank
. Press the 'Add' button

The new party role is displayed at the bottom of the screen

== How do I update a party role for a billing account?
The only field that can be updated for a party role is the 'Thru Date'. If any other details need to be amended then
the entry will need to be deleted and then recreated.

. Select the 'Roles' sub menu
. Locate the entry that needs to be amended
. Enter or use the lookup to enter the 'Thru Date'
. Press the 'Update' button for the entry


== How do I delete a party role from a billing account?
. Locate the entry that needs to be deleted
. Press the 'Delete' button next to the entry
. The entry will be removed from the bottom of the screen
