////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Edit Agreement Terms
Agreement Terms are the rules that make up the agreement.
Agreements may have a one or more terms.

Examples of agreement terms from a sales and purchase viewpoint include the following:

* Payment due within a certain timeframe (eg 30 days)
* Discounts for early payment
* Specifying Late fee penalties
* Purchasing agreements
* Specifying commission rates
* Exclusive Relationship

NOTE: Agreements can also be specified for Employment, Legal, Non Compete etc.

Agreement terms are configured by linking them to the Invoice Item Type.

IMPORTANT: The drop down box for 'Invoice Item Type' contains what appears to be duplicates for items such as
           'Invoice Fee', 'Invoice Discount', 'Invoice Finished Good Item' etc. +
           These are NOT duplicates +
           - one of these entries refers to the Sales Invoice +
           - and the other refers to the Purchase Invoice. +
           As the descriptions are exactly the same it is impossible to know which refers to which
           so needs to be done using trial and error!

== How do I add a payment term for 30 days?
. Select 'Payment Net Days' from the 'Term Type Id' drop down box
. Enter '30' in the 'Term Days' field
. Press the 'Submit' button


== How do I add a discount term of 2% if paid within 10 days?
. Select 'Payment Discounted if paid with Specified Days' from the 'Term Type Id' drop down box
. Enter '2' in the 'Term Value' field
. Enter '10' in the 'Term Days' field
. Press the 'Submit' button


== How do I specify pricing in a specific currency only for thiscustomer or supplier?
This is done using the 'Agreement Items' sub menu

== How do I delete a payment term?
. Locate the payment term required
. Press the 'Remove'on the entry that needs to be removed
