////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for View Foreign Exchange Rates
OFBiz currently allows you to input to 3 different rates for the same currency using the 'Purpose' field.
With this you can specify whether the conversion is to be used internally, externally or leave the field blank.
Also the start and end date for a conversion can be specified beforehand.

== How do I add a new foreign exchange rate?
To add a new rate for US Dollars (USD) to Euro (EUR)

* Using the drop down box on the 'From Currency' field, select 'American Dollar - USD'
* Using the drop down box on the 'To Currency' field, select 'Euro - EUR'
* The 'Purpose' field can be left blank or you can select 'Internal Conversion' or 'External Conversion' from the drop down list
* Enter the exchange rate in the 'Rate' field (eg 0.72883)
* Enter the 'From Date' (NOTE: If left blank then will default to the current date and time)
* Leave the 'Thru Date' blank
* Click the 'Update Foreign Currency Rates' button
* The new foreign exchange rate will be displayed


== How do I update an existing foreign exchange rate?
NOTE: Existing foreign exchange rates cannot be updated - instead the existing rate is expired and a new rate is created.

Currently up to 3 different exchange rates can be created by using the 'Purpose' field to distinguish them.

== How do I delete a foreign exchange rate?
Foreign exchange rates cannot be deleted.
Existing rates can be expired by entering a new exchange rate for the same currency and purpose.