////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Billing Account Orders
This sub menu lists the details of any Sales Orders that have been charged to the billing account.

A Sales Order is charged to a billing account by selecting the billing account as the Payment Method.

NOTE: The details displayed here in conjunction with the 'Payments' sub menu could also be used to generate
    a customer statement or account showing details of customer activity during a specified time period.