////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Agreement Item Products
This screen is used to link a specific product or products to an agreement.
This can be useful for restricting a discount or product pricing to a particular product (or range of products) for a specific customer.

== How do I add a product to an agreement item?
. Press the 'New Product' button
. The 'Edit Agreement Item Product' screen is displayed
. Manually enter or use the lookup to select the 'Product Id'
. Enter the 'Price' to be associated to the product for this agreement item
. Press the 'Submit' button

== How do I update a product linked to an agreement item?
. Select the product required by clicking on the 'Product Id'
. The 'Edit Agreement Item Product' screen is displayed
. Update the 'Price' for the product (NOTE: Only product price is available for update)
. Press the 'Submit' button

== How do I delete a product from an agreement item?
. Press the 'Remove' button on the entry that needs to be deleted

== Help Edit Agreement Item Product
This screen is used to create or update a product entry for an agreement item.
