////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Variance Reason GL Accounts
The Variance Reason / GL Account default is used for mapping any stock differences to a particular general ledger account.
If there are variances in the number of products that are in stock then this affects the value of inventory in the general ledger.
By using this GL default you can offset any differences in stock to the relevant general ledger account.

The number of products (or items) in stock can vary. +
These differences can be caused by numerous reasons. +
Some of these could be as follows:

* Products have been damaged
* Products were lost or stolen
* Products were found
* Under or over supply of a Product from a Supplier (eg. You have ordered 10 and 11 are delivered....)
* Free samples or giveaways to potential clients

NOTE: These mappings are used in Catalog Manager when a manual inventory adjustment is done through the Inventory Item screens.

== How do I add a new Variance Reason / GL Account mapping?
There are 6 mappings that come as part of the OFBiz demo data.

. Select the 'Variance Reason Id' from the drop down list
. Select the 'GL Account Type Id' to map it to from the drop down list
. Press the 'Add' button
. The new 'Variance Reason / GL Account Type' mapping is displayed in the list at the bottom of the screen

== How do I update a Variance Reason / GL Account mapping?
. Select the 'Variance Reason Id' from the drop down list
. Select the updated 'GL Account Type Id' to map it to from the drop down list
. Press the 'Add' button
. The updated 'Variance Reason / GL Account Type' mapping is displayed in the list at the bottom of the screen

== How do I remove a Variance Reason / GL Account mapping?
. Press the 'Remove' button next to the entry that you want to delete
. The entry is removed from the list of entries displayed
