////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Send Per Email
This is used to send a copy of the invoice details to one or more email addresses.
The invoice is included as an attachment and the user can add a simple accompanying email message.

== How do I send a copy of an invoice via email?
. Select the 'Send per Email' sub menu
. The 'Send per Email' default screen will be displayed
. Enter the 'From Email Address' +
  (NOTE TO CHECK: Shouldnt this be defaulted from the user login.....????)
. Leave the 'To Email Address' as it is as this will be defaulted using the customer details from the invoice
. If required enter the 'Copy Email address' for anyone that needs to be copied on the email
. Leave the 'Subject' as the default of 'Please find attached invoice'
. Leave the 'Other Currency' box blank +
  (NOTE TO CHECK: Investigate what effect this has on the email.....)
. Enter a short email message in the 'Email Body'
. Press the 'Submit' button
