////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Manual Transaction

The Manual Electronic Transaction screen allows the user to manually input and process payment related transactions.

Options available include the following:

* Authorising payment transactions
* Refunding payments
* Payment Re-Authorisation
* Payment Capture


== How do I create a manual electronic transaction?
. Select the 'Payment Method Type' (eg Credit Card)
. Select the 'Product Store'
. Select the 'Transaction Type' +
  (NOTE: This is the type of transaction that needs to be created, eg authorisation, capture,refund etc) +
  Additional fields will be displayed
. Enter the required details (eg name, credit card, billing address, amount etc)
. Press the 'Submit' button

A transsaction will be created that can be viewed via the Gateway Transactions screen

NOTE: TO CHECK: Possible bug as could not get this to work using 'Payment Authorisation Service' and error message appeared
     regarding a missing parameter missing for Order Preference Id but the Order Preference Id was not displayed on the screen
