////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Find Financial Account Transactions
A transaction is an entry that is shown on the financial account.

Transactions can be one of the following types:

* Deposits
* Withdrawals
* Adjustments

Transactions are used to show entries and the financial history of the financial account.
Similar to a bank account or credit card statement the transaction will show details of what was spent or paid into the account.

Some transaction totals have been added to this screen to help as part of the reconciliation processes.
Additional details available include number of transactions, transaction totals and status.

== How do I find transactions for a Financial Account?
* Press the 'Search' button
* A list of transactions for the financial account will be displayed
