////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for New Payment
This screen is used to create a new payment.
Payments can be incoming (eg from a customer) or outgoing (eg to a supplier).
Payment types are used to describe what the payments are used for in the system.

Examples of incoming payment types are as follows:

* Customer Deposit
* Customer Payment
* Interest In

Examples of outgoing payment types are as follows:

* Commission Payment
* Pay Check
* Income Tax Payment
* Vendor Payment


== How do I create a new incoming payment?
. Press the 'Create New Payment' button
. The New Incoming Payment / New Outgoing Payment screen is displayed
. Leave 'Organization Party Id' with its default of 'Company'
. Select the 'Payment Type Id' from the drop down box +
  (NOTE: This is currently limited to the following: Customer Deposit, Customer Payment, Interest In and Gift Certificate Deposit)
. Enter the payment amount in the 'Amount' field
. Enter or use the lookup to find the 'From Party Id'
. Select the 'Payment Method Type' from the drop down box (eg how the payment was paid - cash, cheque, money order etc)
. Leave the 'Currency' field with its default of 'USD' +
  (NOTE: This default comes from Company)
. Press the 'Create' button
. The payment header is created and the default header screen will be displayed subsection content

NOTE: TO CHECK Need to understand what happens if customer pays in a currency that is not the company default.... +
      if the exchange rate is specified then I think it should convert the currency to the default currency for accounting purposes.... +
      need to investigate and test.

== How do I create a new outgoing payment?
. Press the 'Create New Payment' button
. The New Incoming Payment / New Outgoing Payment screen is displayed
. Leave 'Organization Party Id' with its default of 'Company'
. Select the 'Payment Type Id' from the drop down box +
  (NOTE: This is currently limited to 11 entries including Commission Payment, Customer Refund, Vendor Payment, Income Tax Payment)
. Enter the payment amount in the 'Amount' field
. Enter or use the lookup to find the 'To Party Id'
. Select the 'Payment Method Type' from the drop down box +
  (eg how the payment is to be paid - cash, cheque, money order etc)
. Leave the 'Currency' field with its default of 'USD' +
  (NOTE: This default comes from Company)
. Press the 'Create' button
. The payment header is created and the default header screen will be displayed subsection content
