////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Payment Type GL Account Type
The Payment Type GL Account Type Id is used to translate (or map) the different payment types to a specific GL Account Type Id.
The GL Account Type Id is then used via the 'GL Account Type Id' defaults to translate to one side of a journal entry.

NOTE: This GL Account default is used to link to another one of the GL Account defaults.

A Payment Type is just a way to categorize transactions.

Examples of Payment Types could be as follows:

* Commission Payments
* Customer Payments
* Vendor (or Supplier) Payments
* Customer Refunds
* Customer Prepayments or Deposits

These payment types can then be mapped to the required account type in the Chart of Account.

Examples of these type of mappings could be as follows:

* Customer Payments are mapped to Account Receivable
* Vendor (or Supplier) Payment are mapped to Account Payable
* Customer Refunds are mapped to Customer Credits

== How do I add a Payment Type / GL Account Type Id mapping?
There are currently 14 different Payment Type / GL Account Types mappings that come as part of the demo data with OFBiz
 and should cover a good variety of payment related transactions.

. Select the 'Payment Type Id' from the drop down list
. Select the 'GL Account Type Id' to map it to from the drop down list
. Press the 'Save' button
. The new 'Payment Type / GL Account Type' mapping is displayed in the list at the bottom of the screen

== How do I update a Payment Type / GL Account Type Id mapping?
A Payment Type / GL Account Type mapping cannot be updated directly but needs to be removed then re-created.
If you try to update an existing entry you will get an 'duplicate key' error message.

. Press the 'Remove' button next to the entry that you want to update
. The entry is removed from the list of entries displayed
. Select the 'Payment Type Id' from the drop down list
. Select the updated 'GL Account Type Id' to map it to from the drop down list
. Press the 'Save' button
. The new 'Payment Type / GL Account Type' mapping is displayed in the list at the bottom of the screen

== How do I remove a Payment Type / GL Account Type Id mapping?
. Press the 'Remove' button next to the entry that you want to delete
. The entry is removed from the list of entries displayed
