////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for List Agreement Geo
This screen is used to display a list of the geographical locations that are valid for the agreement item.

== How do I create a new geographical location for an agreement item?
. Press the 'New' button
. The 'Edit Agreement Geographical Application' screen is displayed
. Use the drop down box to select the 'Geo Id'
. Press the 'Submit' button

== How do I delete a geographical location for an agreement item?
. Press the 'Delete' button for the entry that needs to be deleted

== Help Edit Agreement Geo
This screen is used to create a geographical location for an agreement item.

NOTE: A new entry can be created or removed but not updated.
