////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Find Purchase Invoices By Due Date
This screen allows the user to search for and locate Purchase Invoices based on their due date.

The 'Due Date' can be defined as the last possible date that payments can be received for the invoice without triggering any
late payment penalties.

The 'Invoice Date' can be defined as the date that the invoice was created and this is normally based on when products were
received or services were provided.

NOTE: TO CHECK: See if the same bug that exists with Sales Invoices is here too.

A Purchase Invoice may be due to be paid immediately or you may be given a 'grace period' after which the invoice is due.

== How do I find Purchase Invoices by Due Date?
. Press the 'Find Purchase Invoices by Due Date' button
. The Find Purchase Invoices by Due Date screen is displayed
. Enter the 'Organization Party Id' (eg. Normally this will be Company)
. Enter the 'Party Id' that the Purchase Invoice (eg. Normally this will be the Supplier Party Id)
. Enter a number in the 'Days Offset' field that represents the number of in which the invoice will become due +
  (eg If an invoice is due to be paid in 5 days then enter 5 or greater)
. Press the 'Select' button
