////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Help for Agreement Work Effort Applications
This screen is used to link a work effort to the whole agreement or an individual agreement item.

== How do I add a work effort to an agreement?
. Use the drop down box to select the 'Agreement Item Seq Id'
. Use the lookup to select the 'Workeffort Id'
. Press the 'Add' button
. The new entry is displayed in the lower part of the screen


== How do I update a work effort for an agreement?
Work efforts can only be added or deleted.
They cannot be updated

== How do I delete a work effort from an agreement?
. Press the 'Delete' button for the entry that needs to be deleted
