////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Facility

The Facility Manager is used to manage a warehouse, a store with related inventory.

All operations relating to stock:

* defining locations (in a hierarchical and multi-level ways)
* receiving
* picking, packing
* shipping
* transfer
* return
* physical inventory
* ...

== Facility management in UI

=== Receive Return
For details about Sale Return look at <<Return Process Overview>>

IMPORTANT: What the customer needs from you at this point are three pieces of information to include on the _outside_ of
the package he is returning:

. His original *OrderNumber*.
. This *Return Number* (shown in the screen after the words 'Receive Return'and highlighted inside the link box).
. The exact *Return Address* where you want him to return the item(s). +
  That may be different from the address shown on the package he received.

They should keep this information available for themselves in case they need to call back to check on the status of their return.

[glossary]
== Facility Glossary

[#INVENTORY]
Inventory:: These are goods are held for sale to customers. Inventory is also referred to a Stock. Inventory can be items
that are bought for resale or it can be products that are manufactured and sold to the customer.

[#STOCK]
Stock:: These are goods are held for sale to customers. Stock is also referred to as Inventory.
Stock can be items that are bought for resale or it can be products that are manufactured and sold to the customer.

