////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Facility

The Facility Manager is used to manage a warehouse, a store with related inventory.

All operations relating to stock:

* defining locations (in a hierarchical and multi-level ways)
* receiving
* picking, packing
* shipping
* transfer
* return
* physical inventory
* ...

[glossary]
== Facility Glossary

[#INVENTORY]
Inventory:: These are goods are held for sale to customers. Inventory is also referred to a Stock. Inventory can be items
that are bought for resale or it can be products that are manufactured and sold to the customer.

[#STOCK]
Stock:: These are goods are held for sale to customers. Stock is also referred to as Inventory.
Stock can be items that are bought for resale or it can be products that are manufactured and sold to the customer.

