////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Help for Webtools Main page.

This is the default screen for the Webtools application. +
Several links are present on this page to access specific tool screens directly. +
Using the application menu you can select the tool you need.

* The link:[Logging] section is used to view and configure the OFBiz system logs.
* The link:[Cache & Debug] section is used to monitor the OFBiz cache system status.
           You can even set or clear some cache content or force Garbage collection with this tool.
* The link:[Artifact Info] section is used to navigate through all OFBiz artifact files. When accessing this section
           the complete OFBiz code base is scanned and a list of all artifacts is offered to the user to be navigated.
           Please note that the initial scan can take a while to be completed.
* The link:[Entity Engine] section is used to interact with the entities defined in the system.
           You can view the entity structures, search for entity content, navigate though related entities, etc.
* The link:[Service Engine] section is used to interact with the services defined in the system.
           You can view all services details, monitor the jobs that are running, the active threads.
           You can even manually run a service or schedule a periodic/delaied job execution.
* The link:[Import/Export] section is used to transfer entity content from the OFBiz system to external systems and viceversa.
           Various import/export systems and formats are available.
* The link:[Configuration] section is used to set parameters for the OFBiz system.
