////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Order Option Settings

There are the same options list for each Ship Group, except for internal and ship Notes

* _Shipping methods_ +
     Select the radio button for the preferred shipping method. Consider the customer's desired delivery date, the availability
     of product, your order processing time, and the transportation time required before agreeing with the customer to
     a specific mode of shipping. +
     Note how the cost of each method is already determined and displayed for you.
     Let the customer know the cost involved and obtain his consent to the cost. +
     Parameters about shipping cost are associated with Product Store (entered in first screen).
* _Single or multiple shipments_ +
     Sometimes the customer needs to have all parts of the order available at the same time; they will elect to wait until
     all of the items are available before shipping. Others want whatever items are available immediately and prefer not
     to wait for the rest. Select the radio button to match their preference, but explain that an additional shipping cost
     might be incurred.
* _Special Instructions_ +
     If you get them, record any special instructions here. These will appear on the Pick Sheets.
* _Gift? / Gift Message_ +
     The Yes radio button selection will direct packers to Gift Wrap if that was requested in the order.
     Also, it directs them to attach the Message which follows in the next section.
* _Ship Before / After Date_ (optional) +
    The customer could have any one of many different reasons for wanting the order to be shipped before or after
    a specific date. For example, budget that must be spent within a certain quarter would require the order be
    fulfilled before the end of the quarter. Similarly, if the item is not budgeted until next quarter,
    but they want to receive it early within that quarter, they might specify the first day of the next business quarter. +
    Use the popup calendar to identify and insert the date.
