////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Order Entry Init

Order Entry begin with this screen. Using the top portion labeled "Sales Order" identify the Party placing the order, either
with their User Login Id (when a ecommerce customer give it to you) or their Party Id. The lookup can help you to search the
Id if you have only name, or other details.

* _Sales Order vs. Purchase Order_ +
    Disregard the Purchase Order section of this screen. That is only used when you (as a representative of your company) are
    ordering product or services from another vendor for your company's use.
* _Product Store_ +
    It is probable that your CSR (Customer Service Representative) is processing orders for more than one 'Store' which
    could be an actual physical presence or a virtual shopping center seen on-line by the customer. +
    Confirming the correct Store at this point is critical.
* _Sales Channel_ +
    How did this order reach you? Here are some possibilities:
    .. The customer is standing in front of you at your terminal, probably in an actual store front -- POS Channel.
    .. The customer called in the order and you are on the phone with them at this time -- phone channel.
    .. You are reading from a fax sheet, an e-mail printout, a letter or order form -- FAX channel, e-mail channel,
      or snail mail channel, as appropriate.
    .. Some other party gathered one or more orders together and has forwarded a consolidated order to you -- affiliate channel.
    .. You are not taking the order but it is being processed through the ecommerce website -- defaults the category
      to web channel.

= Order Currency, Agreements, and Ship Dates

On a back office perspective, order entry can be use on a B2B context,

* order Name and PO number are customer informations
* default currency used for this order
* Catalog and Dates are use as default value on next screen
* Across the top bar is the link button [Continue] to go to the next step
