////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Set Shipping address and Group

On this screen it's possible to choose

* the delivery address and/or create a new one,
* to create multiple shipping group, and so multiple delivery address or multiple delivery date
* the party to shipping to if it's not the same as which one ordered

= Set Item to ShipGroup

If you have defined multiple ship group, in this screen you can choose for each item (and each quantity) with which
group it will be ship