////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= JobShop, or ProductionRun
Jobshop is the generic term to manage Production Run

The JobShop is used to manage and track all the manufacturing or assembling work. +
The work (or job) carried out in the JobShop is called a Production Run.

Production Runs can also be called Work Orders.

Production Runs are the work list of the manufacturing department and include details of:

* the product to be manufactured
* the raw materials or sub assemblies to use
* the steps needed to make the finished product

“Production Runs” are the to do or work lists of the manufacturing department. +
Each manufacturing job, batch, or run is done based on a production run.

In OFBiz Jobshop you can

* Create a new ProductionRun
* Manage ProductionRun
  ** its tasks
  ** the materials needed
  ** fixedAsset need (machine)
  ** Parties working
* Associate ProductionRun
* View cost associated
* declare all actions done on a ProductionRun

JobShop menu is the default screen for manufacturing.

Productions Runs can be created manually or automatically. +
To create one manually:

. Click the "Create a Production Run" button

To locate an existing Production Run

. Click "Find"
. A list of any existing Production Runs will be displayed
. Click the Production Run Id to view the Production Run details

Production Runs cannot be deleted but they can be cancelled instead.

== ProductionRun management in UI
=== Find production run
In this screen you can search for existing production runs.
You can also create new production runs by clicking 'Create new production run'

=== Create production run
In this screen you can create a new production run.

. Select the product that needs to be manufactured.
. Set the quantity to produce and the start date.
. Subsequently set the warehouse and the routing ID.
. Give the production run a name and optionally a description.
. Set the field for 'Create dependent production runs' to yes if you want the system to automatically create
   the production runs of sub assemblies or components.
. Click the button 'Submit' to save the changes.

=== Display production run
This screen provides the details of the production run. +
It also provides overviews of related orders, tasks, material, equipment and notes.

include::HELP-mfg-EditProductionRun.adoc[leveloffset=+2]

=== Display production run tasks
This screen provides an overview of all routing tasks connected to the production run. +
From here you can also add a new or modify an existing routing task to the production run.

=== Display production run materials
This screen provides an overview of materials connected to the production run. +
From here you can also connect new materials to the production run.

=== Display production run equipment
This screen provides an overview of the equipment related to the production run. +
From here you can also connect new equipment to the production run.

=== Display production run assocs
This screen provides overviews of mandatory and dependent associated production runs.

=== Display production run content
This screen provides an overview of all connected content to the production run.

=== Display production run costs
This screen provides overviews of the costs of routing tasks of the production run and the cost of routings
 of the production run.

