////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= About Manufacturing and MRP

OFBiz Manufacturing & MRP is a highly functional seamless application that
contains everything you need to run an efficient and successful manufacturing
business.

Key features include:

* Bill of Materials
* Manufacturing Routing and Tasks
* Production Planning
* Production Costing
* Equipment Billing
* Raw Materials Procurement

This guide gives you the basics you need to get up and running with OFBiz for Manufacturing & MRP.

It contains a quick overview of some common manufacturing concepts, a list of the
setup required and an example for you to work through.

By the end of the document you should have the enough information to begin your
own manufacturing setup in OFBiz.

== What is Manufacturing?
Manufacturing is the “act of making something out of raw materials”. The 'something' that is manufactured
 is generally a product that can be on sold to customers.

Manufacturing is not only an industrial activity carried out in a factory, it can also be any range of tasks
 that result in an end product. So, even if you only assemble products you can still make use of OFBiz Manufacturing & MRP.

== What is MRP?
MRP is a three-letter abbreviation that is always used in conjunction with manufacturing – so what exactly is it?

MRP stands for “Material Requirement Planning”.  It’s a computer program that, when run regularly,
helps a business to plan what to manufacture and when to manufacture it.

It also has the added benefit of letting you know when to buy raw materials to meet your manufacturing commitments.

The MRP tool comes with OFBiz ‘out of the box’.

