////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Calendar
To be able to do planification, it's necessary to know when each resources (machine) are available.

Calendar help you to define each period with availability.


== Calendar management in UI
=== Kalenders aanmaken en vinden
Dit schermt stelt je in staat nieuwe productiekalenders te definieren. +
Tevens worden hier de beschikbare kalenders getoond.

Vanaf hier kun je doorklikken naar:

* kalenders
* kalenderweken

==== Nieuwe kalender aanmaken
Klik op de knop 'Nieuwe kalender' om een nieuwe kalender te definieren.

==== Overzicht kalenders
Dit overzicht toont de beschikbare kalenders. +
Klik op de kalender ID (in de eerste kolom) om een kalender aan te passen. +
Klik op de knop 'Wis' om een kalender te verwijderen.


=== Wijzigen kalender
In dit scherm kun je de omschrijving en de gekoppelde kalenderweek definitie van de kalender wijzigen.

=== Kalenderweken
Dit scherm toont de kalenderweken die opgenomen kunnen worden in een productiekalender. +
Het scherm stelt je tevens in staat een kalenderweek toe te voegen en te wijzigen.


=== Aanmaken en wijzigen kalenderweek
In dit scherm kun je nieuwe kalenderweken aanmaken en bestaande wijzigen.

Geef de nieuwe kalenderweek een naam en een omschrijving. +
Zet voor iedere dag de starttijd en de capaciteit.

=== Kalender uitzonderingsweken
Dit scherm toont de uitzonderingsweken van een productiekalender. +
Het scherm stelt je tevens in staat een uitzonderingsweek toe te voegen en te wijzigen.

=== Kalender uitzonderingsdagen
Dit scherm toont de uitzonderingsdagen van een productiekalender. +
Het scherm stelt je tevens in staat een uitzonderingsdag toe te voegen en te wijzigen.
