////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= MRP
MRP stands for “Material Requirement Planning”. It’s a computer program that,
when run regularly, helps a business to plan what to manufacture and when to
manufacture it.

It also has the added benefit of letting you know when to buy raw materials to meet
your manufacturing commitments.

Running MRP is multiple step :

. “MRP” tab and run the MRP report
. view the MRP results
. use the requirement generated to buy order or run productionRun

== MRP management in UI
=== Run MRP
This screen enables you to run an MRP

=== Reports
This screen enables you to get a report on an MRP.

=== MRP Log
This screen displays an overview of the MRPs that ran. +
The second overview in this screen displays the MRPs that are scheduled to run.
From here you can also search for MRPs

=== Shipment plans
This screen provides an overview of all shipment plans.