////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Calendar
To be able to do planification, it's necessary to know when each resources (machine) are available.

Calendar help you to define each period with availability.


== Calendar management in UI
=== Find calendars
This screen displays an overview of exisiting production calendars. +
From this screen you can

* select one to edit it
* create a new calendar by clicking 'New Calendar'

=== Create/modify calendar
In this screen you can create new calendars and change existing calendars.

=== Find calendar weeks
This screen displays an overview all calendar weeks From here you can create new calendar weeks.

=== Create/edit calendar week
In this screen you can define a new calendar week and modify an existing calendar week.

For a new calendar week give it a name and a description. +
Set for each day the start time and the capacity.

=== Calendar exception week
This screen displays a list of the exception weekks of the calendar. +
In this screen you can also add a new exception week to the overview.

=== Calendar exception day
This screen displays a list of the exception days of the calendar. +
In this screen you can also add a new exception day to the curent calendar.
