////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Routing
Routing is used to Link the tasks (routingTask) together in the sequence they need to be performed
to produce final product.

Routing is used, when a productionRun is created for a product, the default routing associated to the product
 is "duplicate" for the productionRun. +
All its routing-tasks are "duplicated" in the productionRun.


== Routing management in UI
=== Werkplan aanmaken en vinden
Dit scherm biedt de mogelijkheid om werkplannen aan te maken en te vinden.

==== Werkplan aanmaken
Klik op de knop 'Nieuw werkplan' om een nieuw werkplan aan te maken.

==== Werkplan zoeken en vinden
Vul de parameters in en klik op de 'zoek' knop. +
Worden resultaten gevonden, dan worden deze getoond in de sectie onder het zoek deel.


=== Route aanmaken en wijzigen
In dit scherm kun je een nieuwe route aanmaken en een bestaande wijzigen.


=== Koppeling werkplan-taak wijzigen
Dit scherm toont gekoppelde werkplan taken en biedt de mogelijkheid werkplan taken te koppelen.

==== Koppelen
Selecteer de werkplan taak, geef het een volgnummer en zet de van- en tot-datum.

==== Overzicht
Onder het formulier wordt het overzicht van gekoppelde werkplan taken getoond. +
Klik op een werkplan taak om deze te openen. +
Klik op de 'Wis'-knop om de koppeling te verwijderen.


=== Koppeling product werkplan wijzigen
In dit scherm kun je de koppelingen van een werkplan met producten wijzigen. +
Tevens toont het scherm de gekoppelde producten.

==== Nieuwe koppeling definieren
Selecteer het product, zet de hoeveelheid en de van- en tot-datum. +
Klik op de button om het op te slaan.