////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Datamodel component
The Apache OFBiz® Project
Release trunk

This is the core component in the OFBiz Base Application stack as it holds all entity definitions used by OFBiz in the various base and special purpose components. Entity definitions define the tables required in the RDBMS to create, read, update and delete records.

For an overview of the data models included, take a look at the code (look into \*code*.xml files).
