////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Human Resources

The OFBiz Human Resources system is one of the core application components and has
all of the functionality you need to manage your business employees as well as the 
recruitment process. It is well integrated with other components especially 
Accounting to manage Payroll and any specific  employee agreements.

include::_include/hr-intro.adoc[leveloffset=+1]

include::_include/hr-employee-positions.adoc[leveloffset=+1]

include::_include/hr-employees.adoc[leveloffset=+1]

include::_include/hr-employments.adoc[leveloffset=+1]

include::_include/hr-performance-review.adoc[leveloffset=+1]

include::_include/hr-qualifications.adoc[leveloffset=+1]

include::_include/hr-recruitment.adoc[leveloffset=+1]

include::_include/hr-skills.adoc[leveloffset=+1]

include::_include/hr-resumes.adoc[leveloffset=+1]

include::_include/hr-training.adoc[leveloffset=+1]

include::_include/hr-leave.adoc[leveloffset=+1]

include::_include/hr-security.adoc[leveloffset=+1]

include::_include/hr-global-settings.adoc[leveloffset=+1]

include::_include/hr-glossary.adoc[leveloffset=+1]
