###############################################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
###############################################################################
rest-api.auth.baseSecurityGroupPermission = REST-API_ADMIN

### Configures jackson serialization inclusion. Possible values are:
#   ALWAYS,NON_NULL,NON_ABSENT,NON_EMPTY,NON_DEFAULT,CUSTOM,USE_DEFAULTS
rest-api.jackson.serialization.inclusion.value=NON_NULL
rest-api.jackson.serialization.inclusion.content=NON_NULL

###openAPI specification
rest-api.info.version = 1.0.0
rest-api.info.title = OFBiz REST APIs
rest-api.info.description = Open API specification for OFBiz RESTful APIs.
rest-api.info.termsOfService = http://www.apache.org/licenses/LICENSE-2.0.html
rest-api.info.contact.name = OFBiz DEV API Team
rest-api.info.contact.email = dev@ofbiz.apache.org
rest-api.info.contact.url = https://ofbiz.apache.org/
rest-api.info.license.name = Apache 2.0
rest-api.info.license.url = http://www.apache.org/licenses/LICENSE-2.0.txt
rest-api.server.description = Server Hosting the REST API
