////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
[glossary]
= Party Glossary

[#AGREEMENT]
Agreement:: An agreement is a way of recording a business arrangement or contract that your business makes with
other companies or individuals. For more details have a look to <<_agreements>> management in accounting component.

[NOTE]
Examples: Customer or Supplier payment terms (eg.30 days to pay);  Discounts (e.g products or volume);
Commissions; Customer Contracts (agreement to sell x number of widgets for y price, or sell at y price for a certain time frame)

[#PERSON]
Person::
Person is a human being as distinguished from a party group which is an organization.
Human beings and organizations have different attributes i.e. People have first and
last names while groups have group names. Both person and party group are types
 of parties and share information and processes common to <<PARTY,parties>>.

[#SECURITY_GROUP]
Security Group:: A  security group is a collection (or a set) of application privileges that can be assigned to a user login id.
A user can be assigned to multiple security groups

[NOTE]
Example: FULLADMIN; BIZADMIN; ECOMMERCE_CUSTOMER.

[#SUPPLIER]
Supplier:: Role of a party that something if purchased from

[#VENDOR]
Vendor::
Role of a party that sells something with the system


